[package]
name = "ql-adapters"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
ql-core = { path = "../ql-core" }
ql-mef = { path = "../ql-mef" }
ql-semantic = { path = "../ql-semantic" }
ql-wiki = { path = "../ql-wiki" }
ql-service = { path = "../ql-service" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }

[lints]
workspace = true
