// 2026-09-06 — Round 3: fill the reserved M1-4.5 space with the full harmonic/musical genesis
// from the current ql-mef musical canon (code + current docs authoritative).
// Target: node M1-4.5 only. No children exist under M1-4.5 — account lands as properties.
// All statements idempotent (SET; corrections preserve former values via coalesce).
// Apostrophes escaped with backslash per skills/bimba-cypher/SKILL.md §6.

// S1 — the chain overview: the reservation fulfilled, the plumbing stage by stage
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_genesis_chain = 'The reserved space filled (2026-09-06, round 3): the full harmonic/musical genesis as the current ql-mef canon holds it, landed as this c_2_musical_* family. The plumbing, stage by stage: # (the generative parent, not a position — Paramaśiva and Paraśakti as one act, (No)Name and Power as its two faces) → the source equation 0/1 + 1/0 = 1/1 = 100% → the two Spanda equations (First 3:3 horizontal, Second 4:2 vertical) → the cross-comparison (4:2)/(3:3) → 16/9 and the canonical ratio field (1/1, 4/3, 3/4, 3/2, 2/3, 16/9, 9/8, 2/1) → the two bases (chromatic 9/8, fifths 3/2) as two traversal-orderings of one Z12 substrate → the six-family pairing grammar (A/B/C within-pass + D1-D3 conjugate completion) → the twelve L/L′ lens anchors → the 8+4 explicate/implicate partition and the 3x3 squares → the Context-Frame diatonic cut and the seven modes → the 84 mode-tonic landscape → the Jankó 4:2 figure as playable projection. Standing (unchanged from the reservation): the kernel coordinates are the 1, this derivation their 0 — the definitional layer of what # amounts to, retroactively explaining the ordering law that governs them; here that 0-layer acquires its harmonic face. Composition, not duplication: M1-4 c_2_exponent_genesis already reads 2^4/3^2 as the position hexad and the 12-ring; M1-3 c_2_double_cover_reading already reads the equation as the two circuits; M1-3-4 c_2_equation_as_frames already maps it to CF1-CF7. This family is the musical register of the same derivation — each stage cross-references rather than re-derives. Executable ground: crates/ql-mef/src/music.rs derive_pre_m_music(), MUSICAL_HARMONIC_VERSION 1.0.0.';

// S2 — the Spanda equations, musical face
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_spanda_equations = 'First Spanda (3:3 horizontal): 0 = (0/0) → ((0/1)/(1/0)) → T0 || T1 → (1/0 + 0/1) → 1/1 = 100%. T0 and T1 are the two co-arising directional faces of one self-differentiation — direct/bimba and prime/pratibimba, never a primary phase with a later inverse attached (executable faces: QlFace::Direct and QlFace::Conjugate, carrying MefUnitFace::Name and Power; Day = direct, Night = prime). They are the two helices of M1-3\'s double-cover reading sounded as the two whole-tone sixfolds. Second Spanda (4:2 vertical): 100% = 2^6 + 6^2 = 64 + 36; 64/36 = 16/9 = (4/3)^2 = 2^4/3^2 — the totality-ratio as the ratio-face of 1/1, an identification across registers (standing-identity register vs internal-proportion register), not a fractional equality. The musical birth is the cross-comparison (4:2)/(3:3) = (4/3, 2/3): holding the Second Spanda\'s vertical reading of the sixfold against the First\'s horizontal reading yields the manifestation-fourth and the grounding-fifth directly; slash-inversion gives 3/4 and 3/2; the octave follows as 4/3 · 3/2 = 2/1; the square gives (4/3)^2 = 16/9; the differences give 9/8 twice (3/2 ÷ 4/3 and 2/1 ÷ 16/9). The ratios are not imported from music theory — they are the matheme reading its own double-reading of unity aloud. Grounding of the circle both bases presuppose: the First Spanda\'s collision-dynamic (Galperin blocks — 3 collisions at mass-ratio 1, approaching π as the ratio grows; the 3-to-π measurement-depth continuum between rational finite count and irrational cyclic measure); and rhythm becomes pitch across the ~20 Hz perceptual-fusion threshold — pitch is the uniform rhythmic substrate at audible density, so the generative capacity covers rhythm-through-frequency-through-pitch-through-harmony as one continuum.';

// S3 — the canonical ratio field as code holds it
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_ratio_field = 'The canonical set as code holds it (CANONICAL_RATIOS in crates/ql-mef/src/music.rs; fixtures/music/harmonic-ratios-v1.tsv): 1/1 unity (standing-identity, totality-as-unity); 4/3 manifestation-fourth; 3/4 recognition-fourth; 3/2 aspirational fifth (the harmonic-architecture generator); 2/3 grounding fifth; 16/9 QL totality / doubled-fourth (one epogdoon short of octave); 9/8 epogdoon / tick / whole-tone (the generative-incompleteness residue); 2/1 octave (cyclic closure with residue). Three convergent derivations of 9/8: 2/1 ÷ 16/9 (octave-residue of totality); 3/2 ÷ 4/3 (fifth-minus-fourth); 72/64 (the Paraśakti double-cover reading, 2·6^2 over 2^6 — the same seam M3-0 holds as the epogdoon two-way door and M2-5 as the 72-to-64 compression). Two load-bearing identities: 16/9 × 9/8 = 2/1 — totality plus tick equals octave; the system almost-doubles and falls short by exactly one whole-tone, and that residue is the spanda operationalised as recursive cycle; and 4/3 × 9/8 × 4/3 = 2/1 — the diatonic octave as tetrachord + epogdoon-bridge + tetrachord, the 4+4′ inner-fours partition rendered as pure Pythagorean scale-architecture. The tetractys closure (3+1+4+2 = 10) and the 12-position double-cover reading (3+3+4+2 = 12) are carried by M1-4\'s exponent genesis and are not restated here.';

// S4 — the two bases and the Z12 substrate
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_two_bases = 'Two equally-foundational generator-traversals of one chromatic substrate, co-foundational, neither prior. Chromatic basis: generator 9/8 (+2 semitones; pitch law (2n) mod 12, conjugate face +1); cross-helix conjugate axis = the semitone (minimum quantum). Fifths basis: generator 3/2 (+7 semitones; pitch law (7n) mod 12, conjugate face +6); cross-helix conjugate axis = the tritone (maximum symmetric). At L0 chromatic: direct C D E F♯ G♯ A♯, prime C♯ D♯ F G A B. At L0 fifths: direct C G D A E B, prime F♯ C♯ G♯ D♯ A♯ F. Both unions are the same complete Z12 pitch-class substrate — the same twelve pitch classes in two traversal orders; (4+2)+(4′+2′) = 6+6 = 12: the conjugate-doubling of the sixfold IS the chromatic doubling into twelve. The Name progression (Truth→Mind→Word→Logos→Son→Image) sounds as whole-tone ascent in the chromatic basis and as fifth-stack in the fifths basis — same articulation, different generator-ordering. Chromatic foregrounds the tick (uniform rhythmic traversal, time\'s count); fifths foregrounds tonal architecture (harmonic generation, time\'s harmony). The conjugate-relation as such is basis-invariant; what differs is which interval the conjugate-cross enacts — minimum-quantum versus maximum-symmetric.';

// S5 — the pairing grammar, canon law
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_pairing_grammar = 'The six universal pairing families (canon per ql-core RelationFamily and AUTHORED_INTERVAL_REFERENCES, and v3 Reference Table 9): A adjacent-articulation {(0,1),(2,3),(4,5)} — the natural dyads, each position with its immediate companion; B offset-transition {(1,2),(3,4),(5,0)} — the crossing-pairs stepping from one natural dyad into the next, (5,0) enacting the §5→§0′ closure-with-enrichment; C converse-mirror {(0,5),(1,4),(2,3)} — the mirror-pairs summing to 5 across the hexad centre. The double membership of (2,3) in both A and C is canonical — the midpoint self-mirror at the hexad midline. D1→D2→D3 are conjugate-completion degrees owned by ql_core build_d_modulation_frame(), NOT a fourth relation family beside A/B/C: D1 = selected direct pair (2 coordinates); D2 = one-sided conjugate expansion (3); D3 = complete conjugate square (4). The semantic cross operators (CrossSamePosition, CrossTransform, CrossRequire, CrossComplete) are separate kernel relations over the same field, not additional D degrees. Interval realisations are basis-specific: A = whole-tones ×3 (chromatic) or fifths ×3 (fifths); B = whole-tone ×2 + minor 3rd at cycle-close (chromatic) or perfect-4th ×2 + minor 2nd (fifths); C = minor-7th (the 16/9 totality span), tritone, whole-tone (chromatic) or major-7th, minor-3rd, fifth (fifths); D1 = semitone ×6 (chromatic) or tritone ×6 (fifths); D3 identical to bimba A/B/C (helix-invariance). The grammar is universal — derived from positional architecture, operating identically on both bases, all twelve lens anchors, the diatonic architecture and all modal rotations.';

// S6 — lens anchors, 8+4, 3x3 squares
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_lens_anchors = 'Twelve tonic anchors derived from the lenses\' own kernel coordinates (the lens_anchor transform — a derivation from existing addresses, never a new numbering): chromatic C D E F♯ G♯ A♯ / C♯ D♯ F G A B; fifths C G D A E B / F♯ C♯ G♯ D♯ A♯ F — twelve distinct pitches per basis; the L/L′ family turns the same twelve kernel addresses into the twelve tonic/epistemic anchorings (C/C′, P/P′, L/L′ share the address field; KernelRelationId::FamilySamePosition ties the views). Lens-modulation IS epistemic-mode-modulation. The 8+4 architectural partition: 8 explicate-articulating positions (positions 1-4 on both faces — the inner-fours; the sounded 8-fold scale, the Barry-Harris foundational scale with the 8th note landing chord-tones on downbeats) + 4 implicate-nodal positions (0 and 5 on both faces — the outer-twos; cymatic anchor-points, boundary conditions for the standing-wave equation, structurally still, not sounded content). What sounds = the 8; what anchors the form = the 4. The 3x3 squares: each within-pass family (A, B, C) crossed with the helix-doubling over its three pairs = 9 squares per basis, 8 unique tetrads — A-sq2 = C-sq3 at the (2,3) midpoint self-mirror, basis-invariant.';

// S7 — the CF cut, modes, and the 84 landscape
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_cf_modes_84 = 'The Context-Frame grammar cuts the diatonic: ContextFrameCut::canonical() selects #0, #1, #2, #2′, #3′, #4′, #5′ — the same seven frames M1-3-4 holds as the equation\'s own architecture (c_2_equation_as_frames) — rendered through the chromatic substrate at the lens anchor (cf_diatonic_cut). At L0 chromatic: C D E F G A B, form sequence Name-Name-Name-Power-Power-Power-Power — 5 inner-fours + 2 outer-twos = 7 degrees; the 3 unpicked inner-fours (F♯, G♯, D♯) stand as complexification-hooks, the 2 unpicked outer-twos (A♯, C♯) as pure cymatic anchors. The seven ModeKind rotations (Ionian, Dorian, Phrygian, Lydian, Mixolydian, Aeolian, Locrian) ground CF1-CF7 respectively, each with its authored form-selection pattern (Dorian N-N-P-P-P-P-N; Phrygian N-P-P-P-P-N-N; Lydian N-N-N-N-P-P-P; Mixolydian N-N-N-P-P-P-N; Aeolian N-N-P-P-P-N-N; Locrian N-P-P-N-P-N-N). Major/minor is a derivation, not a description: the conjugate-form selection at the three character-determining degrees 3, 6, 7 — major selects Name-Power-Power (E Word, A Love, B Work); minor selects Power-Name-Name (E♭ Need, A♭ Son, B♭ Image); anyone who has heard a major triad against a minor one has heard precisely that. The complete landscape: 12 derived lens anchors × 7 CF groundings = 84 structural mode-tonic instances, preserving lens identity, CF identity, pitch content and form-selection provenance (mode_tonic_landscape() in code) — the matheme\'s complete musical expression at the mode-tonic level.';

// S8 — the Jankó 4:2 figure
MATCH (n {coordinate:'M1-4.5'})
SET n.c_2_musical_janko_figure = 'The Jankó 4:2 instrument Figure (docs/music/JANKO-QL-INSTRUMENT-FIGURE.md): the historical 1882 six-row isomorphic surface — two interleaved whole-tone row families, each sounding note repeated as three touch-points; along a row the next key is a whole tone away, the neighbouring interleaved row gives the semitone-shifted complementary whole-tone collection. The project-level Figure (historical instrument fact and QL interpretation kept rigorously distinct; never historical proof, never derivational authority — a controller projection over the already-derived object): row-family colour counts 4 white : 2 black ↔ Second Spanda 4:2, and 3 white : 3 black ↔ First Spanda 3:3 — both Spanda partitions co-present on alternate rows of one instrument; the two interleaved whole-tone row families ↔ the two chromatic direct/prime helices (union Z12); the cross-row diagonal semitone ↔ the cross-face conjugate axis. Value: repeated fingering under transposition (the isomorphic regularity) makes the sixfold/two-face substrate directly visible and playable; the controller consumes canonical kernel IDs and adds no music semantics of its own; the standard piano remains a legal rendering.';

// S9 — provenance + timestamp
MATCH (n {coordinate:'M1-4.5'})
SET n.c_3_musical_canon_refs = 'Canon refs: crates/ql-mef/src/music.rs (MUSICAL_HARMONIC_VERSION 1.0.0; MUSICAL_DERIVATION_SOURCE_PATH docs/sources/ql-musical-derivation-v3.md, blob 6414c56c6241c3da46e1ea6fdcd7a09b6b66c5aa; vendor commit 9429a9fb5173f32138799046e8e2a4d7a2d86968); crates/ql-mef/src/music_completion.rs (MUSICAL_COMPLETION_VERSION 1.0.0); tests: musical_harmonic_system.rs, musical_completion.rs, musical_traversal_classification.rs; docs/music/PRE-M-MUSICAL-DERIVATION-v1.md; docs/music/JANKO-QL-INSTRUMENT-FIGURE.md; fixtures/music/harmonic-ratios-v1.tsv + source-provenance-v1.tsv. Authority order observed: current code and current docs over older map names; this round wrote only M1-4.5 (round 3 of 2026-09-06).',
    n.c_3_updated_at = '2026-09-06';

// S10 — q_1 correction: the B/C family letters were swapped relative to the executable canon
MATCH (n {coordinate:'M1-4.5'})
SET n.q_1_former_reading = coalesce(n.q_1_former_reading, n.q_1_harmonic_families_abc),
    n.q_1_harmonic_families_abc = 'What M1-4.5 IS, on its relational face: the **harmonic meta-families A/B/C** by which the matheme\'s positions stand in audible relation. **A — Being / adjacent-articulation**: `A = {(0,1),(2,3),(4,5)}`, the natural dyads, each position with its immediate companion — co-constitution as adjacency (whole-tones in the chromatic basis, perfect fifths in the fifths basis). **B — Becoming / offset-transition**: `B = {(1,2),(3,4),(5,0)}`, the crossing-pairs, each stepping from one natural dyad into the next, the `(5,0)` pair being the `§5→§0` enrichment itself — synthesis crossing the limit of its own knowing back into ground (whole-tone ×2 + minor 3rd at cycle-close in the chromatic basis; perfect-4th ×2 + minor 2nd in the fifths basis). **C — Knowing-Unknowing / converse-mirror**: `C = {(0,5),(1,4),(2,3)}`, the mirror-pairs summing to 5 across the hexad\'s centre — complement recognised as structural interdependence (minor-7th C–A♯ = the 16/9 totality-span, tritone D–G♯, whole-tone E–F♯; major-7th, minor-3rd, perfect-fifth in the fifths basis). The double membership of `(2,3)` in both A and C is canonical: Word and Logos, the self-inverting core, adjacent-Being and mirror-complement at once. [Corrected 2026-09-06, round 3, to the executable canon — ql-core RelationFamily and AUTHORED_INTERVAL_REFERENCES; v3 §II-2.5 and Reference Table 9: the family letters B and C were previously swapped, and the (2,3) double membership previously read as A-and-B; the former reading is preserved in q_1_former_reading.]';

// S11 — q_0 correction: reciprocal pair was written 3/4, 2/3; canon is 3/4, 3/2
MATCH (n {coordinate:'M1-4.5'})
SET n.q_0_former_reading = coalesce(n.q_0_former_reading, n.q_0_foundational_ratios_inherited),
    n.q_0_foundational_ratios_inherited = 'M1-4.5\'s ground is the canonical ratio-set the prior beats hand it, the harmonic-inheritance from the Second Spanda\'s accounting. Its void-pole is the standing identity itself before any scale is built: `0/1 + 1/0 = 1/1 = 100%`, and `100% = 2⁶ + 6² = 64 + 36`, whose proportion reduces `64/36 = 16/9 = (4/3)² = 2⁴/3²`. The cross-reading `(4:2)/(3:3) = (4/3, 2/3)` already yields the fourth and the grounding fifth; slash-inversion gives the reciprocals `3/4, 3/2`; the octave follows as `4/3 · 3/2 = 2/1`. The boxed inheritance — `1/1, 4/3, 3/4, 3/2, 2/3, 16/9, 9/8, 2/1` — sits complete but un-orchestrated. The from-where is the matheme\'s pure ratio-body: every consonance the ear trusts present as number, none yet assigned a meta-frame, the harmonic seed awaiting its expansion into the architecture of worlds. [Corrected 2026-09-06, round 3: the reciprocal pair was previously written `3/4, 2/3`; canon (v3 §II-5.3, and CANONICAL_RATIOS) holds `4/3 ↔ 3/4`, `2/3 ↔ 3/2`; the former reading is preserved in q_0_former_reading.]';
