// Generated by `ql vak workflow-types` from the QL-MEF Rust contract
// (crates/ql-mef/src/vak_workflow_types.rs over vak_profile.rs and context_frame.rs).
// Do not hand-edit: crates/ql-mef/tests/vak_workflow_types.rs fails on drift.
// Types only. Factory's restricted workflow compiler admits this module through its
// registered domain adapter and lowers a unit's `composition` to its native C-prime
// execution binding. Nothing here grants execution, identity or authority.

export type WorkflowTypesContract = "ql.vak-workflow-types/v1";

/** The QL profile contract the lowered binding declares. */
export type ProfileContract = "ql.vak-composition.profile/v1";

/** CPF: dialogical or authorised-undertaking participation. */
export type Participation = "dialogical" | "authorised-undertaking";

/** CT: content kind; CT4b' specialises contextual content. */
export type ContentType = "CT0" | "CT1" | "CT2" | "CT3" | "CT4" | "CT4b'" | "CT5";

/** CP: 4.0 ground, 4.1 definition, 4.2 operation, 4.3 pattern, 4.4 context, 4.5 integration. */
export type ContentPosition = "4.0" | "4.1" | "4.2" | "4.3" | "4.4" | "4.5";

/** CF: the source-defined constitutional/relational frame. */
export type ContextFrame = "CF1" | "CF2" | "CF3" | "CF4" | "CF5" | "CF6" | "CF7";

/** CFP0-5: single voice, parallel/chord, chain/melody, fusion, sustained/drone, nested/canon. */
export type ThreadForm = "CFP0" | "CFP1" | "CFP2" | "CFP3" | "CFP4" | "CFP5";

/** CS0-5: exact source-defined paired passage; direction and extent stay distinct. */
export type ContextSequence = "CS0" | "CS1" | "CS2" | "CS3" | "CS4" | "CS5";

export type InquiryDirection = "forward" | "returning";

/** Musical role of each thread form. */
export type ThreadMusicalRole = {
  readonly CFP0: "single-voice";
  readonly CFP1: "chord";
  readonly CFP2: "melody";
  readonly CFP3: "fusion";
  readonly CFP4: "drone";
  readonly CFP5: "canon";
};

/** Each passage as its retained forward/returning position pairs. */
export type Passages = {
  readonly CS0: readonly [readonly ["4.0", "4.5"], readonly ["4.1", "4.4"], readonly ["4.2", "4.3"], readonly ["4.3", "4.2"], readonly ["4.4", "4.1"], readonly ["4.5", "4.0"]];
  readonly CS1: readonly [readonly ["4.0", "4.5"], readonly ["4.1", "4.4"]];
  readonly CS2: readonly [readonly ["4.0", "4.5"], readonly ["4.1", "4.4"], readonly ["4.2", "4.3"]];
  readonly CS3: readonly [readonly ["4.0", "4.5"], readonly ["4.1", "4.4"], readonly ["4.2", "4.3"], readonly ["4.3", "4.2"]];
  readonly CS4: readonly [readonly ["4.0", "4.5"], readonly ["4.4", "4.1"], readonly ["4.5", "4.0"]];
  readonly CS5: readonly [readonly ["4.0", "4.5"], readonly ["4.5", "4.0"]];
};

/** Constitutional voices hosted by Anima; role contributions, not product identities. */
export type ConstitutionalVoice = "Nous" | "Logos" | "Eros" | "Mythos" | "Anima" | "Psyche" | "Sophia";

/** Each constitutional voice's source frame. */
export type VoiceFrame = {
  readonly Nous: "CF1";
  readonly Logos: "CF2";
  readonly Eros: "CF3";
  readonly Mythos: "CF4";
  readonly Anima: "CF5";
  readonly Psyche: "CF6";
  readonly Sophia: "CF7";
};

/** Named specialists: selectable contributions, never a compulsory swarm. */
export type Specialist = "Anansi" | "Janus" | "Moirai" | "Mercurius" | "Agora" | "Zeithoven";

/** Specialist offices as the full-field lock states them. */
export type SpecialistOffice = {
  readonly Anansi: "Investigate gaps and the authored/implemented relation; coordinate and blueprint work.";
  readonly Janus: "Relate temporal occasions; temporal and threshold work.";
  readonly Moirai: "Supply Klotho/Lachesis/Atropos evidence, query and reflection modes; GraphRAG distillation.";
  readonly Mercurius: "Carry cross-domain translation; Kairos and qualitative temporal patterns.";
  readonly Agora: "Bring plural contributions into evaluation; aggregation and skill/plugin absorption.";
  readonly Zeithoven: "Develop the next score; creative advance and skill/agent creation.";
};

/** S5-prime disclosure/crystallisation/Return; not an eighth constitutional peer. */
export type DisclosureOrgan = "Aletheia";

export type SourceRevision = {
  readonly ref: string;
  readonly revision: string;
};

/** An authorised undertaking names its authority; a dialogical act carries none. */
export type CPrimeParticipation =
  | { readonly CPF: "dialogical"; readonly authority?: never }
  | { readonly CPF: "authorised-undertaking"; readonly authority: string };

/** One unit's authored C-prime. Factory lowers it to its native execution binding; the unit's subjectRef is the binding subject and `actor` must be a declared participant. */
export type CPrime = CPrimeParticipation & {
  readonly CT: ContentType;
  readonly CP: ContentPosition;
  readonly CF: ContextFrame;
  readonly CFP: ThreadForm;
  readonly CS: ContextSequence;
  readonly direction: InquiryDirection;
  readonly actor: string;
  readonly interpretation: SourceRevision;
  readonly whole: string;
  readonly resolvePath: string;
  readonly contextResolution: string;
  readonly sources: ReadonlyArray<string>;
};
