// Decan -> its Minor Arcana pip card (36). QL-MEF #135, owner-approved 28 Sep 2026.
// Deterministic join: the decan's m_2_3_tarot_card names the card (c_1_name); the card's own
// c_3_astrological states the same decan. The card then carries the existing chain
// card <-GOVERNS_TAROT_EXPRESSION- codon reflection -REFLECTS_DNA_FORM-> codon. Additive: MERGE only.

// @probe existing decan->pip relations (expect 0 before apply, 36 after)
MATCH (:Decan)-[r:EXPRESSES_AS_TAROT_PIP]->() RETURN count(r) AS n;

// @apply decan -> pip card (36)
MATCH (a:Bimba {coordinate:'M2-3-1-0-0'}), (b:Bimba {coordinate:'M3-4-1-1'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-0-0', c_0_target_coordinate:'M3-4-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Aries Decan 1 is expressed as the pip card Two of Wands (Mars in Aries (March 21-30))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-0-1'}), (b:Bimba {coordinate:'M3-4-1-2'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-0-1', c_0_target_coordinate:'M3-4-1-2', c_1_relation_family:'correspondential', c_1_relation_description:'Aries Decan 2 is expressed as the pip card Three of Wands (Sun in Aries (March 31-April 10))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-0-2'}), (b:Bimba {coordinate:'M3-4-1-3'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-0-2', c_0_target_coordinate:'M3-4-1-3', c_1_relation_family:'correspondential', c_1_relation_description:'Aries Decan 3 is expressed as the pip card Four of Wands (Venus in Aries (April 11-20))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-1-0'}), (b:Bimba {coordinate:'M3-4-1-4'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-1-0', c_0_target_coordinate:'M3-4-1-4', c_1_relation_family:'correspondential', c_1_relation_description:'Leo Decan 1 is expressed as the pip card Five of Wands (Saturn in Leo (July 23-August 1))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-1-1'}), (b:Bimba {coordinate:'M3-4-1-5'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-1-1', c_0_target_coordinate:'M3-4-1-5', c_1_relation_family:'correspondential', c_1_relation_description:'Leo Decan 2 is expressed as the pip card Six of Wands (Jupiter in Leo (August 2-11))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-1-2'}), (b:Bimba {coordinate:'M3-4-1-6'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-1-2', c_0_target_coordinate:'M3-4-1-6', c_1_relation_family:'correspondential', c_1_relation_description:'Leo Decan 3 is expressed as the pip card Seven of Wands (Mars in Leo (August 12-22))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-2-0'}), (b:Bimba {coordinate:'M3-4-1-7'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-2-0', c_0_target_coordinate:'M3-4-1-7', c_1_relation_family:'correspondential', c_1_relation_description:'Sagittarius Decan 1 is expressed as the pip card Eight of Wands (Mercury in Sagittarius (November 23-December 2))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-2-1'}), (b:Bimba {coordinate:'M3-4-1-8'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-2-1', c_0_target_coordinate:'M3-4-1-8', c_1_relation_family:'correspondential', c_1_relation_description:'Sagittarius Decan 2 is expressed as the pip card Nine of Wands (Moon in Sagittarius (December 3-12))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-2-2'}), (b:Bimba {coordinate:'M3-4-1-9'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-2-2', c_0_target_coordinate:'M3-4-1-9', c_1_relation_family:'correspondential', c_1_relation_description:'Sagittarius Decan 3 is expressed as the pip card Ten of Wands (Saturn in Sagittarius (December 13-21))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-0-0'}), (b:Bimba {coordinate:'M3-4-4-4'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-0-0', c_0_target_coordinate:'M3-4-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Taurus Decan 1 is expressed as the pip card Five of Pentacles (Mercury in Taurus (April 21-30))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-0-1'}), (b:Bimba {coordinate:'M3-4-4-5'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-0-1', c_0_target_coordinate:'M3-4-4-5', c_1_relation_family:'correspondential', c_1_relation_description:'Taurus Decan 2 is expressed as the pip card Six of Pentacles (Moon in Taurus (May 1-10))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-0-2'}), (b:Bimba {coordinate:'M3-4-4-6'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-0-2', c_0_target_coordinate:'M3-4-4-6', c_1_relation_family:'correspondential', c_1_relation_description:'Taurus Decan 3 is expressed as the pip card Seven of Pentacles (Saturn in Taurus (May 11-20))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-1-0'}), (b:Bimba {coordinate:'M3-4-4-7'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-1-0', c_0_target_coordinate:'M3-4-4-7', c_1_relation_family:'correspondential', c_1_relation_description:'Virgo Decan 1 is expressed as the pip card Eight of Pentacles (Sun in Virgo (August 23-September 1))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-1-1'}), (b:Bimba {coordinate:'M3-4-4-8'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-1-1', c_0_target_coordinate:'M3-4-4-8', c_1_relation_family:'correspondential', c_1_relation_description:'Virgo Decan 2 is expressed as the pip card Nine of Pentacles (Venus in Virgo (September 2-11))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-1-2'}), (b:Bimba {coordinate:'M3-4-4-9'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-1-2', c_0_target_coordinate:'M3-4-4-9', c_1_relation_family:'correspondential', c_1_relation_description:'Virgo Decan 3 is expressed as the pip card Ten of Pentacles (Mercury in Virgo (September 12-22))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-2-0'}), (b:Bimba {coordinate:'M3-4-4-1'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-2-0', c_0_target_coordinate:'M3-4-4-1', c_1_relation_family:'correspondential', c_1_relation_description:'Capricorn Decan 1 is expressed as the pip card Two of Pentacles (Jupiter in Capricorn (December 22-30))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-2-1'}), (b:Bimba {coordinate:'M3-4-4-2'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-2-1', c_0_target_coordinate:'M3-4-4-2', c_1_relation_family:'correspondential', c_1_relation_description:'Capricorn Decan 2 is expressed as the pip card Three of Pentacles (Mars in Capricorn (January 1-10))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-2-2'}), (b:Bimba {coordinate:'M3-4-4-3'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-2-2', c_0_target_coordinate:'M3-4-4-3', c_1_relation_family:'correspondential', c_1_relation_description:'Capricorn Decan 3 is expressed as the pip card Four of Pentacles (Sun in Capricorn (January 11-20))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-0-0'}), (b:Bimba {coordinate:'M3-4-3-7'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-0-0', c_0_target_coordinate:'M3-4-3-7', c_1_relation_family:'correspondential', c_1_relation_description:'Gemini Decan 1 is expressed as the pip card Eight of Swords (Jupiter in Gemini (May 21-31))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-0-1'}), (b:Bimba {coordinate:'M3-4-3-8'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-0-1', c_0_target_coordinate:'M3-4-3-8', c_1_relation_family:'correspondential', c_1_relation_description:'Gemini Decan 2 is expressed as the pip card Nine of Swords (Mars in Gemini (June 1-10))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-0-2'}), (b:Bimba {coordinate:'M3-4-3-9'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-0-2', c_0_target_coordinate:'M3-4-3-9', c_1_relation_family:'correspondential', c_1_relation_description:'Gemini Decan 3 is expressed as the pip card Ten of Swords (Sun in Gemini (June 11-20))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-1-0'}), (b:Bimba {coordinate:'M3-4-3-1'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-1-0', c_0_target_coordinate:'M3-4-3-1', c_1_relation_family:'correspondential', c_1_relation_description:'Libra Decan 1 is expressed as the pip card Two of Swords (Moon in Libra (October 14-23))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-1-1'}), (b:Bimba {coordinate:'M3-4-3-2'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-1-1', c_0_target_coordinate:'M3-4-3-2', c_1_relation_family:'correspondential', c_1_relation_description:'Libra Decan 2 is expressed as the pip card Three of Swords (Saturn in Libra (October 24-November 2))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-1-2'}), (b:Bimba {coordinate:'M3-4-3-3'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-1-2', c_0_target_coordinate:'M3-4-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Libra Decan 3 is expressed as the pip card Four of Swords (Jupiter in Libra (November 3-12))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-2-0'}), (b:Bimba {coordinate:'M3-4-3-4'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-2-0', c_0_target_coordinate:'M3-4-3-4', c_1_relation_family:'correspondential', c_1_relation_description:'Aquarius Decan 1 is expressed as the pip card Five of Swords (Venus in Aquarius (January 21-30))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-2-1'}), (b:Bimba {coordinate:'M3-4-3-5'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-2-1', c_0_target_coordinate:'M3-4-3-5', c_1_relation_family:'correspondential', c_1_relation_description:'Aquarius Decan 2 is expressed as the pip card Six of Swords (Mercury in Aquarius (January 31-February 9))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-2-2'}), (b:Bimba {coordinate:'M3-4-3-6'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-2-2', c_0_target_coordinate:'M3-4-3-6', c_1_relation_family:'correspondential', c_1_relation_description:'Aquarius Decan 3 is expressed as the pip card Seven of Swords (Moon in Aquarius (February 10-18))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-0-0'}), (b:Bimba {coordinate:'M3-4-2-1'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-0-0', c_0_target_coordinate:'M3-4-2-1', c_1_relation_family:'correspondential', c_1_relation_description:'Cancer Decan 1 is expressed as the pip card Two of Cups (Venus in Cancer (June 21-July 1))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-0-1'}), (b:Bimba {coordinate:'M3-4-2-2'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-0-1', c_0_target_coordinate:'M3-4-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Cancer Decan 2 is expressed as the pip card Three of Cups (Mercury in Cancer (July 2-11))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-0-2'}), (b:Bimba {coordinate:'M3-4-2-3'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-0-2', c_0_target_coordinate:'M3-4-2-3', c_1_relation_family:'correspondential', c_1_relation_description:'Cancer Decan 3 is expressed as the pip card Four of Cups (Moon in Cancer (July 12-22))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-1-0'}), (b:Bimba {coordinate:'M3-4-2-4'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-1-0', c_0_target_coordinate:'M3-4-2-4', c_1_relation_family:'correspondential', c_1_relation_description:'Scorpio Decan 1 is expressed as the pip card Five of Cups (Mars in Scorpio (October 24-November 2))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-1-1'}), (b:Bimba {coordinate:'M3-4-2-5'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-1-1', c_0_target_coordinate:'M3-4-2-5', c_1_relation_family:'correspondential', c_1_relation_description:'Scorpio Decan 2 is expressed as the pip card Six of Cups (Sun in Scorpio (November 3-12))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-1-2'}), (b:Bimba {coordinate:'M3-4-2-6'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-1-2', c_0_target_coordinate:'M3-4-2-6', c_1_relation_family:'correspondential', c_1_relation_description:'Scorpio Decan 3 is expressed as the pip card Seven of Cups (Venus in Scorpio (November 13-22))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-2-0'}), (b:Bimba {coordinate:'M3-4-2-7'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-2-0', c_0_target_coordinate:'M3-4-2-7', c_1_relation_family:'correspondential', c_1_relation_description:'Pisces Decan 1 is expressed as the pip card Eight of Cups (Saturn in Pisces (February 19-28))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-2-1'}), (b:Bimba {coordinate:'M3-4-2-8'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-2-1', c_0_target_coordinate:'M3-4-2-8', c_1_relation_family:'correspondential', c_1_relation_description:'Pisces Decan 2 is expressed as the pip card Nine of Cups (Jupiter in Pisces (March 1-10))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-2-2'}), (b:Bimba {coordinate:'M3-4-2-9'}) MERGE (a)-[x:EXPRESSES_AS_TAROT_PIP]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-2-2', c_0_target_coordinate:'M3-4-2-9', c_1_relation_family:'correspondential', c_1_relation_description:'Pisces Decan 3 is expressed as the pip card Ten of Cups (Mars in Pisces (March 11-20))', c_2_relation_type:'EXPRESSES_AS_TAROT_PIP', c_2_relation_kind:'decan tarot pip', c_2_join_basis:'decan m_2_3_tarot_card = card c_1_name', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};

// @report
MATCH (a:Decan)-[r:EXPRESSES_AS_TAROT_PIP]->(b) RETURN count(r) AS edges, count(DISTINCT a) AS decans, count(DISTINCT b) AS cards;
