// M3-5 clock inscription: the seed placement of codons on the dual codon clock.
// QL-MEF #135. Additive and idempotent: MERGE only, no DELETE/REMOVE/SET on nodes.
// Run order: every @probe (read-only), then @apply, then @report. Nothing is applied
// without an explicit run of the @apply block.
//
// Clock A (degree -> decan -> codon): each decan's tarot pip is a codon reflection
// (#3-4.0) whose REFLECTS_DNA_FORM already reaches its codon. The join existed only as
// equal card names (decan m_2_3_tarot_card = reflection m_3_4_tarot_card); this makes it
// a typed relation. 36/36 decans match exactly one reflection.
// Backbone: each of the 24 governors (#3-5-q-p) names its season's perfect palindrome in
// c_1_description; this makes that a typed relation to the codon (#3-2).

// @probe existing inscription relations (expect 0 before apply, 60 after)
MATCH ()-[r:CARRIES_PIP_REFLECTION|EMBODIES_PALINDROMIC_CODON]->() RETURN type(r) AS type, count(r) AS n;

// @probe every endpoint exists (expect 60 rows, found=true)
UNWIND [['M2-3-1-0-0','M3-4.0-2-1'], ['M2-3-1-0-1','M3-4.0-2-2'], ['M2-3-1-0-2','M3-4.0-2-3'], ['M2-3-1-1-0','M3-4.0-2-4'], ['M2-3-1-1-1','M3-4.0-2-5'], ['M2-3-1-1-2','M3-4.0-2-6'], ['M2-3-1-2-0','M3-4.0-2-7'], ['M2-3-1-2-1','M3-4.0-2-8'], ['M2-3-1-2-2','M3-4.0-2-9'], ['M2-3-2-0-0','M3-4.0-3-4'], ['M2-3-2-0-1','M3-4.0-3-5'], ['M2-3-2-0-2','M3-4.0-3-6'], ['M2-3-2-1-0','M3-4.0-3-7'], ['M2-3-2-1-1','M3-4.0-3-8'], ['M2-3-2-1-2','M3-4.0-3-9'], ['M2-3-2-2-0','M3-4.0-3-1'], ['M2-3-2-2-1','M3-4.0-3-2'], ['M2-3-2-2-2','M3-4.0-3-3'], ['M2-3-3-0-0','M3-4.0-4-7'], ['M2-3-3-0-1','M3-4.0-4-8'], ['M2-3-3-0-2','M3-4.0-4-9'], ['M2-3-3-1-0','M3-4.0-4-1'], ['M2-3-3-1-1','M3-4.0-4-2'], ['M2-3-3-1-2','M3-4.0-4-3'], ['M2-3-3-2-0','M3-4.0-4-4'], ['M2-3-3-2-1','M3-4.0-4-5'], ['M2-3-3-2-2','M3-4.0-4-6'], ['M2-3-4-0-0','M3-4.0-1-1'], ['M2-3-4-0-1','M3-4.0-1-2'], ['M2-3-4-0-2','M3-4.0-1-3'], ['M2-3-4-1-0','M3-4.0-1-4'], ['M2-3-4-1-1','M3-4.0-1-5'], ['M2-3-4-1-2','M3-4.0-1-6'], ['M2-3-4-2-0','M3-4.0-1-7'], ['M2-3-4-2-1','M3-4.0-1-8'], ['M2-3-4-2-2','M3-4.0-1-9'], ['M3-5-1-0','M3-2-4-4-4'], ['M3-5-1-1','M3-2-4-4-4'], ['M3-5-1-2','M3-2-4-4-4'], ['M3-5-1-3','M3-2-4-4-4'], ['M3-5-1-4','M3-2-4-4-4'], ['M3-5-1-5','M3-2-4-4-4'], ['M3-5-2-0','M3-2-1-1-1'], ['M3-5-2-1','M3-2-1-1-1'], ['M3-5-2-2','M3-2-1-1-1'], ['M3-5-2-3','M3-2-1-1-1'], ['M3-5-2-4','M3-2-1-1-1'], ['M3-5-2-5','M3-2-1-1-1'], ['M3-5-3-0','M3-2-3-3-3'], ['M3-5-3-1','M3-2-3-3-3'], ['M3-5-3-2','M3-2-3-3-3'], ['M3-5-3-3','M3-2-3-3-3'], ['M3-5-3-4','M3-2-3-3-3'], ['M3-5-3-5','M3-2-3-3-3'], ['M3-5-4-0','M3-2-2-2-2'], ['M3-5-4-1','M3-2-2-2-2'], ['M3-5-4-2','M3-2-2-2-2'], ['M3-5-4-3','M3-2-2-2-2'], ['M3-5-4-4','M3-2-2-2-2'], ['M3-5-4-5','M3-2-2-2-2']] AS e
OPTIONAL MATCH (a:Bimba {coordinate:e[0]}) OPTIONAL MATCH (b:Bimba {coordinate:e[1]})
RETURN count(*) AS rows, sum(CASE WHEN a IS NOT NULL AND b IS NOT NULL THEN 1 ELSE 0 END) AS found;

// @apply decan -> pip-card codon reflection (36)
MATCH (a:Bimba {coordinate:'M2-3-1-0-0'}), (b:Bimba {coordinate:'M3-4.0-2-1'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-0-0', c_0_target_coordinate:'M3-4.0-2-1', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 2 of Wands is the codon reflection of TTA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-0-1'}), (b:Bimba {coordinate:'M3-4.0-2-2'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-0-1', c_0_target_coordinate:'M3-4.0-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 3 of Wands is the codon reflection of TTC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-0-2'}), (b:Bimba {coordinate:'M3-4.0-2-3'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-0-2', c_0_target_coordinate:'M3-4.0-2-3', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 4 of Wands is the codon reflection of TGG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-1-0'}), (b:Bimba {coordinate:'M3-4.0-2-4'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-1-0', c_0_target_coordinate:'M3-4.0-2-4', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 5 of Wands is the codon reflection of TAC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-1-1'}), (b:Bimba {coordinate:'M3-4.0-2-5'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-1-1', c_0_target_coordinate:'M3-4.0-2-5', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 6 of Wands is the codon reflection of TCA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-1-2'}), (b:Bimba {coordinate:'M3-4.0-2-6'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-1-2', c_0_target_coordinate:'M3-4.0-2-6', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 7 of Wands is the codon reflection of TCC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-2-0'}), (b:Bimba {coordinate:'M3-4.0-2-7'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-2-0', c_0_target_coordinate:'M3-4.0-2-7', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 8 of Wands is the codon reflection of TAA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-2-1'}), (b:Bimba {coordinate:'M3-4.0-2-8'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-2-1', c_0_target_coordinate:'M3-4.0-2-8', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 9 of Wands is the codon reflection of TCT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-1-2-2'}), (b:Bimba {coordinate:'M3-4.0-2-9'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-1-2-2', c_0_target_coordinate:'M3-4.0-2-9', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 10 of Wands is the codon reflection of TAT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-0-0'}), (b:Bimba {coordinate:'M3-4.0-3-4'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-0-0', c_0_target_coordinate:'M3-4.0-3-4', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 5 of Pentacles is the codon reflection of CGC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-0-1'}), (b:Bimba {coordinate:'M3-4.0-3-5'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-0-1', c_0_target_coordinate:'M3-4.0-3-5', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 6 of Pentacles is the codon reflection of CGG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-0-2'}), (b:Bimba {coordinate:'M3-4.0-3-6'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-0-2', c_0_target_coordinate:'M3-4.0-3-6', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 7 of Pentacles is the codon reflection of CGT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-1-0'}), (b:Bimba {coordinate:'M3-4.0-3-7'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-1-0', c_0_target_coordinate:'M3-4.0-3-7', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 8 of Pentacles is the codon reflection of CTG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-1-1'}), (b:Bimba {coordinate:'M3-4.0-3-8'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-1-1', c_0_target_coordinate:'M3-4.0-3-8', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 9 of Pentacles is the codon reflection of CTT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-1-2'}), (b:Bimba {coordinate:'M3-4.0-3-9'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-1-2', c_0_target_coordinate:'M3-4.0-3-9', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 10 of Pentacles is the codon reflection of CTC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-2-0'}), (b:Bimba {coordinate:'M3-4.0-3-1'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-2-0', c_0_target_coordinate:'M3-4.0-3-1', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 2 of Pentacles is the codon reflection of CCG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-2-1'}), (b:Bimba {coordinate:'M3-4.0-3-2'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-2-1', c_0_target_coordinate:'M3-4.0-3-2', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 3 of Pentacles is the codon reflection of CCT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-2-2-2'}), (b:Bimba {coordinate:'M3-4.0-3-3'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-2-2-2', c_0_target_coordinate:'M3-4.0-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 4 of Pentacles is the codon reflection of CAA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-0-0'}), (b:Bimba {coordinate:'M3-4.0-4-7'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-0-0', c_0_target_coordinate:'M3-4.0-4-7', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 8 of Swords is the codon reflection of GCC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-0-1'}), (b:Bimba {coordinate:'M3-4.0-4-8'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-0-1', c_0_target_coordinate:'M3-4.0-4-8', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 9 of Swords is the codon reflection of GAA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-0-2'}), (b:Bimba {coordinate:'M3-4.0-4-9'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-0-2', c_0_target_coordinate:'M3-4.0-4-9', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 10 of Swords is the codon reflection of GCG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-1-0'}), (b:Bimba {coordinate:'M3-4.0-4-1'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-1-0', c_0_target_coordinate:'M3-4.0-4-1', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 2 of Swords is the codon reflection of GGA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-1-1'}), (b:Bimba {coordinate:'M3-4.0-4-2'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-1-1', c_0_target_coordinate:'M3-4.0-4-2', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 3 of Swords is the codon reflection of GGC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-1-2'}), (b:Bimba {coordinate:'M3-4.0-4-3'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-1-2', c_0_target_coordinate:'M3-4.0-4-3', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 4 of Swords is the codon reflection of GTT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-2-0'}), (b:Bimba {coordinate:'M3-4.0-4-4'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-2-0', c_0_target_coordinate:'M3-4.0-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 5 of Swords is the codon reflection of GAC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-2-1'}), (b:Bimba {coordinate:'M3-4.0-4-5'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-2-1', c_0_target_coordinate:'M3-4.0-4-5', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 6 of Swords is the codon reflection of GAG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-3-2-2'}), (b:Bimba {coordinate:'M3-4.0-4-6'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-3-2-2', c_0_target_coordinate:'M3-4.0-4-6', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 7 of Swords is the codon reflection of GCA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-0-0'}), (b:Bimba {coordinate:'M3-4.0-1-1'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-0-0', c_0_target_coordinate:'M3-4.0-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 2 of Cups is the codon reflection of AAG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-0-1'}), (b:Bimba {coordinate:'M3-4.0-1-2'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-0-1', c_0_target_coordinate:'M3-4.0-1-2', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 3 of Cups is the codon reflection of AAT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-0-2'}), (b:Bimba {coordinate:'M3-4.0-1-3'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-0-2', c_0_target_coordinate:'M3-4.0-1-3', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 4 of Cups is the codon reflection of ACC; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-1-0'}), (b:Bimba {coordinate:'M3-4.0-1-4'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-1-0', c_0_target_coordinate:'M3-4.0-1-4', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 5 of Cups is the codon reflection of ATG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-1-1'}), (b:Bimba {coordinate:'M3-4.0-1-5'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-1-1', c_0_target_coordinate:'M3-4.0-1-5', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 6 of Cups is the codon reflection of AGA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-1-2'}), (b:Bimba {coordinate:'M3-4.0-1-6'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-1-2', c_0_target_coordinate:'M3-4.0-1-6', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 7 of Cups is the codon reflection of AGT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-2-0'}), (b:Bimba {coordinate:'M3-4.0-1-7'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-2-0', c_0_target_coordinate:'M3-4.0-1-7', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 8 of Cups is the codon reflection of AGG; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-2-1'}), (b:Bimba {coordinate:'M3-4.0-1-8'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-2-1', c_0_target_coordinate:'M3-4.0-1-8', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 9 of Cups is the codon reflection of ATT; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M2-3-4-2-2'}), (b:Bimba {coordinate:'M3-4.0-1-9'}) MERGE (a)-[x:CARRIES_PIP_REFLECTION]->(b) ON CREATE SET x += {c_0_source_coordinate:'M2-3-4-2-2', c_0_target_coordinate:'M3-4.0-1-9', c_1_relation_family:'correspondential', c_1_relation_description:'Decan pip card 10 of Cups is the codon reflection of ATA; Clock A: degree -> decan -> codon', c_2_relation_type:'CARRIES_PIP_REFLECTION', c_2_relation_kind:'Clock A seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};

// @apply backbone governor -> its season's perfect-palindrome codon (24)
MATCH (a:Bimba {coordinate:'M3-5-1-0'}), (b:Bimba {coordinate:'M3-2-4-4-4'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-1-0', c_0_target_coordinate:'M3-2-4-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome GGG (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-1-1'}), (b:Bimba {coordinate:'M3-2-4-4-4'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-1-1', c_0_target_coordinate:'M3-2-4-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome GGG (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-1-2'}), (b:Bimba {coordinate:'M3-2-4-4-4'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-1-2', c_0_target_coordinate:'M3-2-4-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome GGG (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-1-3'}), (b:Bimba {coordinate:'M3-2-4-4-4'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-1-3', c_0_target_coordinate:'M3-2-4-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome GGG (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-1-4'}), (b:Bimba {coordinate:'M3-2-4-4-4'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-1-4', c_0_target_coordinate:'M3-2-4-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome GGG (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-1-5'}), (b:Bimba {coordinate:'M3-2-4-4-4'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-1-5', c_0_target_coordinate:'M3-2-4-4-4', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome GGG (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-2-0'}), (b:Bimba {coordinate:'M3-2-1-1-1'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-2-0', c_0_target_coordinate:'M3-2-1-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome AAA (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-2-1'}), (b:Bimba {coordinate:'M3-2-1-1-1'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-2-1', c_0_target_coordinate:'M3-2-1-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome AAA (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-2-2'}), (b:Bimba {coordinate:'M3-2-1-1-1'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-2-2', c_0_target_coordinate:'M3-2-1-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome AAA (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-2-3'}), (b:Bimba {coordinate:'M3-2-1-1-1'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-2-3', c_0_target_coordinate:'M3-2-1-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome AAA (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-2-4'}), (b:Bimba {coordinate:'M3-2-1-1-1'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-2-4', c_0_target_coordinate:'M3-2-1-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome AAA (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-2-5'}), (b:Bimba {coordinate:'M3-2-1-1-1'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-2-5', c_0_target_coordinate:'M3-2-1-1-1', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome AAA (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-3-0'}), (b:Bimba {coordinate:'M3-2-3-3-3'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-3-0', c_0_target_coordinate:'M3-2-3-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome CCC (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-3-1'}), (b:Bimba {coordinate:'M3-2-3-3-3'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-3-1', c_0_target_coordinate:'M3-2-3-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome CCC (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-3-2'}), (b:Bimba {coordinate:'M3-2-3-3-3'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-3-2', c_0_target_coordinate:'M3-2-3-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome CCC (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-3-3'}), (b:Bimba {coordinate:'M3-2-3-3-3'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-3-3', c_0_target_coordinate:'M3-2-3-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome CCC (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-3-4'}), (b:Bimba {coordinate:'M3-2-3-3-3'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-3-4', c_0_target_coordinate:'M3-2-3-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome CCC (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-3-5'}), (b:Bimba {coordinate:'M3-2-3-3-3'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-3-5', c_0_target_coordinate:'M3-2-3-3-3', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome CCC (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-4-0'}), (b:Bimba {coordinate:'M3-2-2-2-2'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-4-0', c_0_target_coordinate:'M3-2-2-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome TTT (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-4-1'}), (b:Bimba {coordinate:'M3-2-2-2-2'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-4-1', c_0_target_coordinate:'M3-2-2-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome TTT (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-4-2'}), (b:Bimba {coordinate:'M3-2-2-2-2'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-4-2', c_0_target_coordinate:'M3-2-2-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome TTT (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-4-3'}), (b:Bimba {coordinate:'M3-2-2-2-2'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-4-3', c_0_target_coordinate:'M3-2-2-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome TTT (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-4-4'}), (b:Bimba {coordinate:'M3-2-2-2-2'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-4-4', c_0_target_coordinate:'M3-2-2-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome TTT (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};
MATCH (a:Bimba {coordinate:'M3-5-4-5'}), (b:Bimba {coordinate:'M3-2-2-2-2'}) MERGE (a)-[x:EMBODIES_PALINDROMIC_CODON]->(b) ON CREATE SET x += {c_0_source_coordinate:'M3-5-4-5', c_0_target_coordinate:'M3-2-2-2-2', c_1_relation_family:'correspondential', c_1_relation_description:'Backbone governor carries the perfect palindrome TTT (its c_1_description); 384 = 360 degree nodes + 24 backbone', c_2_relation_type:'EMBODIES_PALINDROMIC_CODON', c_2_relation_kind:'backbone seed inscription', c_3_dataset_branch:'ql-clock-inscription', c_3_created_at:'2026-09-28T00:00:00.000Z'};

// @report
MATCH (a)-[r:CARRIES_PIP_REFLECTION|EMBODIES_PALINDROMIC_CODON]->(b) RETURN type(r) AS type, count(r) AS n, count(DISTINCT a) AS sources, count(DISTINCT b) AS targets;
