#!/usr/bin/env python3
"""Generate the owner-ruled Bimba map corrections for #135 (rulings on #254, 28 Sep 2026).

D0   Re-author into the live map three facts the July import dropped (they were
     never in the importer's reviewed key table, so they never reached the map):
       - the planetary just octave on #2-5 planets: scalarDegree, intervalFromRoot,
         scaleFunction  -> m_2_5_scalar_degree, m_2_5_interval_from_root,
         m_2_5_scale_function (the importer's m_<root>_<slot> rule);
       - Shem planetaryColor on each Shem -> planet relation -> m_2_4_planetary_color
         (a list: some names carry two literals for the same planet);
       - the codon <-> hexagram pairing, hexagram associatedCodons
         -> m_3_1_associated_codons.
     Values are read from the export the map was seeded from
     (Epi-Logos-C-Experiments daa660c Idea/Bimba/Map/datasets), exactly as written.

COIN The nucleotide values are A=6, T=9, C=8, G=7 (odd = yang: T fire, G air).
     The map's C/G-dependent values were computed with C=7, G=8. Each is
     recomputed; the generator first proves that the old table reproduces every
     current map value, and every write is guarded on that old value.

Read-only against the map (HTTP, accessMode READ). Writes only the .cypher.
"""
from __future__ import annotations

import json
import subprocess
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
EPI = Path(sys.argv[1] if len(sys.argv) > 1 else Path.home() / "Documents/epi/Epi-Logos-C-Experiments")
ENDPOINT = "http://100.92.62.101:7474/db/neo4j/query/v2"
EXPORT = "daa660cbc1b8c5da83828698665a753852cb0287"
OUT = HERE / "2026-09-28-d0-reauthor-and-coin.cypher"
# Applied to the live map 2026-09-28 (owner rulings on #254). Re-running against the
# corrected map proves idempotence: it emits no coin writes and no D0 writes are needed.
OLD = {"A": 6, "T": 9, "C": 7, "G": 8}
NEW = {"A": 6, "T": 9, "C": 8, "G": 7}
NUC = "ATCG"  # map address digits 1..4


def export(path: str):
    raw = subprocess.check_output(["git", "-C", str(EPI), "show", f"{EXPORT}:Idea/Bimba/Map/datasets/{path}"])
    return json.loads(raw.decode("utf-8-sig"), strict=False)


def query(statement: str) -> list:
    body = json.dumps({"statement": statement, "accessMode": "READ"}).encode()
    request = urllib.request.Request(ENDPOINT, data=body, headers={"Content-Type": "application/json"})
    reply = json.load(urllib.request.urlopen(request, timeout=120))
    if reply.get("errors"):
        raise SystemExit(reply["errors"])
    return reply["data"]["values"]


def live(ref: str) -> str:
    """#-coordinate -> the map's M spelling (#2-5-0/1 -> M2-5-(0/1))."""
    parts = ref.lstrip("#").split("-")
    return "M" + "-".join(f"({p})" if "/" in p else p for p in parts)


def lit(value) -> str:
    if isinstance(value, list):
        return "[" + ", ".join(lit(v) for v in value) + "]"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def charges(seq: str, table: dict) -> dict:
    x, y, z = (table[c] for c in seq)
    return {"pp": x + y + z, "nn": x - y - z, "np": x - y + z, "pn": x + y - z}


def main() -> None:
    lines = [
        "// Owner rulings on QL-MEF #254 (28 Sep 2026): D0 re-authoring and the C=8/G=7 coin table.",
        "// Generated by migration/bimba-map/generate_d0_and_coin.py; do not hand-edit.",
        "// Additive for D0 (SET only where absent); the coin writes are guarded on the old value.",
        "",
    ]

    # ---- D0: planetary just octave -------------------------------------------------
    nodes = export("parashakti-deep/nodes-full-detail.json")
    stragglers = export("low-detail/parashakti-stragglers-nodes.json")
    props = {n["coordinate"]: n.get("filteredProps", {}) for n in nodes}
    for n in stragglers:
        props.setdefault(n["coordinate"], n.get("all_props", {}))
    planets = ["#2-5-0/1"] + [f"#2-5-{i}" for i in range(2, 10)]
    lines.append("// @apply D0 planetary just octave (m_2_5_*)")
    written = 0
    for ref in planets:
        p = props.get(ref, {})
        sets = {k: p.get(src) for k, src in (("m_2_5_scalar_degree", "scalarDegree"),
                                              ("m_2_5_interval_from_root", "intervalFromRoot"),
                                              ("m_2_5_scale_function", "scaleFunction")) if p.get(src) not in (None, "")}
        for key, value in sets.items():
            lines.append(f"MATCH (n:Bimba {{coordinate:{lit(live(ref))}}}) WHERE n.{key} IS NULL SET n.{key} = {lit(value)};")
            written += 1
    print("planet values", written)

    # ---- D0: Shem planetaryColor -------------------------------------------------
    rels = export("parashakti-deep/relations.json")
    colours: dict[tuple[str, str], list[str]] = {}
    for r in rels:
        src, tgt = r.get("source") or "", r.get("target") or ""
        colour = (r.get("relProperties") or {}).get("planetaryColor")
        if src.startswith("#2-4.5-") and tgt.startswith("#2-5") and colour:
            bucket = colours.setdefault((live(src), live(tgt)), [])
            if colour not in bucket:
                bucket.append(colour)
    live_edges = {(a, b): t for a, t, b in query(
        "MATCH (a:Bimba)-[r]->(b:Bimba) WHERE a.coordinate STARTS WITH 'M2-4.5-' AND b.coordinate STARTS WITH 'M2-5' "
        "RETURN a.coordinate, type(r), b.coordinate")}
    missing = [k for k in colours if k not in live_edges]
    if missing:
        raise SystemExit(f"export colour edges with no live relation: {missing[:5]}")
    lines += ["", "// @apply D0 Shem planetaryColor on the live Shem -> planet relation (m_2_4_planetary_color)"]
    for (a, b), values in sorted(colours.items()):
        lines.append(f"MATCH (:Bimba {{coordinate:{lit(a)}}})-[r:{live_edges[(a, b)]}]->(:Bimba {{coordinate:{lit(b)}}}) "
                     f"WHERE r.m_2_4_planetary_color IS NULL SET r.m_2_4_planetary_color = {lit(values)};")
    print("shem colour relations", len(colours), "of live", len(live_edges))

    # ---- D0: codon <-> hexagram pairing -------------------------------------------
    mahamaya = export("mahamaya-deep/nodes-full-detail.json")
    pairs = {n["coordinate"]: n["filteredProps"]["associatedCodons"] for n in mahamaya
             if n.get("coordinate", "").startswith("#3-1-") and n["coordinate"].count("-") == 3
             and n.get("filteredProps", {}).get("associatedCodons")}
    lines += ["", "// @apply D0 hexagram associatedCodons (m_3_1_associated_codons)"]
    for ref, codons in sorted(pairs.items()):
        lines.append(f"MATCH (n:Bimba {{coordinate:{lit(live(ref))}}}) WHERE n.m_3_1_associated_codons IS NULL "
                     f"SET n.m_3_1_associated_codons = {lit(codons)};")
    print("hexagram pairings", len(pairs))

    # ---- COIN: recompute C/G-dependent values ---------------------------------------
    lines += ["", "// @apply COIN codon charges, reflection charges, pair sums/differences, nucleotide integrals"]
    checked = changed = 0
    for coord, seq, pp, nn, np_, pn, pattern in query(
            "MATCH (n:Bimba) WHERE (n.coordinate STARTS WITH 'M3-2-' OR n.coordinate STARTS WITH 'M3-4.0-') "
            "AND n.c_3_inner_charge_pp IS NOT NULL RETURN n.coordinate, n.p_3_sequence, n.c_3_inner_charge_pp, "
            "n.c_3_inner_charge_nn, n.c_3_inner_charge_np, n.c_3_inner_charge_pn, n.c_3_charge_pattern"):
        current = {"pp": int(pp), "nn": int(nn), "np": int(np_), "pn": int(pn)}
        if charges(seq, NEW) == current:
            checked += 1
            continue  # already corrected (the migration has been applied)
        if charges(seq, OLD) != current:
            raise SystemExit(f"{coord} {seq}: current charges {current} are not the old-table values")
        checked += 1
        corrected = charges(seq, NEW)
        if corrected == current:
            continue
        sets = ", ".join(f"n.c_3_inner_charge_{k} = {v}" for k, v in corrected.items())
        guard = " AND ".join(f"n.c_3_inner_charge_{k} = {v}" for k, v in current.items())
        if pattern is not None:
            sets += ", n.c_3_charge_pattern = " + lit(" ".join(f"{k}:{corrected[k]}" for k in ("nn", "np", "pn", "pp")))
        lines.append(f"MATCH (n:Bimba {{coordinate:{lit(coord)}}}) WHERE {guard} SET {sets};")
        changed += 1
    print("codon/reflection charge nodes checked", checked, "corrected", changed)

    for coord, seq, total, diff in query(
            "MATCH (n:Bimba) WHERE n.coordinate STARTS WITH 'M3-2-' AND n.c_3_sum_value IS NOT NULL "
            "RETURN n.coordinate, n.p_3_sequence, n.c_3_sum_value, n.c_3_difference_value"):
        x, y = (OLD[c] for c in seq)
        total, diff = int(total), int(diff)
        nx, ny = (NEW[c] for c in seq)
        # The ruling corrects magnitudes; each recorded difference sign is kept
        # (AG=GA and TC=CT are class-stable, M3 unresolved item 2), as the
        # ratified kernel correction M3-COIN-1 keeps them.
        sign = (diff > 0) - (diff < 0)
        want = (nx + ny, sign * abs(nx - ny))
        if (total, diff) == want:
            continue  # already corrected
        if total != x + y or abs(diff) != abs(x - y):
            raise SystemExit(f"{coord} {seq}: pair values are not the old-table values")
        lines.append(f"MATCH (n:Bimba {{coordinate:{lit(coord)}}}) WHERE n.c_3_sum_value = {total} AND "
                     f"n.c_3_difference_value = {diff} SET n.c_3_sum_value = {want[0]}, n.c_3_difference_value = {want[1]};")
        changed += 1

    # Nucleotide integrals: sum of each charge over the 16 codons with that outer nucleotide, / 4.
    codons = [a + b + c for a in NUC for b in NUC for c in NUC]
    for coord, pp, pn, np_, nn in query(
            "MATCH (n:Bimba) WHERE n.coordinate =~ 'M3-2-[1-4]' RETURN n.coordinate, n.c_3_integral_pp, "
            "n.c_3_integral_pn, n.c_3_integral_np, n.c_3_integral_nn"):
        outer = NUC[int(coord.rsplit("-", 1)[1]) - 1]
        def integral(table):
            members = [charges(c, table) for c in codons if c[0] == outer]
            return {k: sum(m[k] for m in members) // 4 for k in ("pp", "pn", "np", "nn")}
        current = {"pp": int(pp), "pn": int(pn), "np": int(np_), "nn": int(nn)}
        if integral(NEW) == current:
            continue  # already corrected
        if integral(OLD) != current:
            raise SystemExit(f"{coord}: integrals {current} are not the old-table values {integral(OLD)}")
        corrected = integral(NEW)
        if corrected != current:
            guard = " AND ".join(f"n.c_3_integral_{k} = {v}" for k, v in current.items())
            sets = ", ".join(f"n.c_3_integral_{k} = {v}" for k, v in corrected.items())
            lines.append(f"MATCH (n:Bimba {{coordinate:{lit(coord)}}}) WHERE {guard} SET {sets};")
            changed += 1
    print("coin writes", changed)

    lines += ["", "// @report", "MATCH (n:Bimba) WHERE n.m_2_5_interval_from_root IS NOT NULL RETURN 'planets' AS k, count(n) AS n",
              "UNION ALL MATCH ()-[r]->() WHERE r.m_2_4_planetary_color IS NOT NULL RETURN 'shem colours' AS k, count(r) AS n",
              "UNION ALL MATCH (n:Bimba) WHERE n.m_3_1_associated_codons IS NOT NULL RETURN 'hexagram pairings' AS k, count(n) AS n;", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT.name, len(lines), "lines")


if __name__ == "__main__":
    main()
