"""Current controlled admission is separate from the historical finite proof.

These run the actual refresh command over copies of the retained source
artifacts. Faults affect qualification only; no numerical expectation is
generated by the fixture producer.
"""
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]
PATHS = (
    "scripts/refresh-m3-parent-consumer.py",
    "fixtures/kernel/m3-parent-consumer-v1.json",
    "fixtures/kernel/m3-finite-proof-v1.json",
    "fixtures/kernel/m3-parent-consumer-current-v1.json",
    "fixtures/kernel/m3-parent-consumer-current-v1.basis.json",
    "fixtures/kernel/m-tree-v1.json",
    "fixtures/kernel/m3-domain-v1.json",
)


class ParentConsumerQualificationTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        for name in PATHS:
            destination = self.root / name
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(ROOT / name, destination)

    def run_refresh(self, *arguments):
        return subprocess.run(
            [sys.executable, str(self.root / PATHS[0]), *arguments],
            capture_output=True, text=True, check=False,
        )

    def read(self, name):
        return json.loads((self.root / name).read_text())

    def mutate(self, name, change):
        value = self.read(name)
        change(value)
        (self.root / name).write_text(json.dumps(value))

    def test_current_check_preserves_every_byte_and_refresh_changes_only_admission(self):
        before = {name: (self.root / name).read_bytes() for name in PATHS}
        result = self.run_refresh("--check")
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(before, {name: (self.root / name).read_bytes() for name in PATHS})
        for name in PATHS[3:5]:
            (self.root / name).unlink()
        result = self.run_refresh()
        self.assertEqual(result.returncode, 0, result.stderr)
        self.assertEqual(before, {name: (self.root / name).read_bytes() for name in PATHS})
        historical = self.read(PATHS[1])
        current = self.read(PATHS[3])
        self.assertNotEqual(current["request"]["registry_revision"], historical["request"]["registry_revision"])
        current["request"]["registry_revision"] = historical["request"]["registry_revision"]
        self.assertEqual(current, historical)
        self.assertEqual(
            hashlib.sha256(before[PATHS[1]]).hexdigest(),
            self.read(PATHS[2])["inputs"][PATHS[1]],
        )

    def test_edited_historical_request_is_refused_against_its_original_proof_lock(self):
        self.mutate(PATHS[1], lambda value: value["request"].update(aperture=3))
        result = self.run_refresh()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("Historical M3 request differs from its retained finite-proof input", result.stderr)

    def test_split_domain_and_registry_source_is_refused(self):
        self.mutate(PATHS[6], lambda value: value.update(source_revision="0" * 64))
        result = self.run_refresh()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("do not share their exact source basis", result.stderr)

    def test_missing_original_source_qualification_is_refused(self):
        self.mutate(PATHS[6], lambda value: value.update(source_files=[]))
        result = self.run_refresh()
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("lacks its exact original Bimba source qualification", result.stderr)

    def test_stale_or_changed_current_determinants_are_refused_without_writes(self):
        self.mutate(PATHS[3], lambda value: value["request"].update(clock_steps=0))
        before = {name: (self.root / name).read_bytes() for name in PATHS}
        result = self.run_refresh("--check")
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("Current controlled M3 fixture/basis is stale", result.stderr)
        self.assertEqual(before, {name: (self.root / name).read_bytes() for name in PATHS})


if __name__ == "__main__":
    unittest.main()
