// Expression development: Anima conducts its constitutional voices over one
// Expression, and Aletheia discloses what was performed and returns it.
//
// A Factory workflow source (restricted TypeScript data, never executed).
// Check it with: factory workflow check workflows/expression-development.workflow.ts --json
// Each unit's `composition` is a QL C-prime; Factory lowers it to its native
// execution binding. Participants, Skills and capabilities are requirements,
// not launched agents, loaded context or grants.
import { defineWorkflow, unit, barrier } from "@epilogos/factory-workflow";
import type { CPrime } from "@epilogos/ql-vak";

const subject = "project:O-I";
const basis = "f7082e5d";
const whole = "central:source:project:O-I:ProjectCentral/now";
const returns = "central:source:project:O-I:ProjectCentral/now";
const cprime = { ref: "ql/interpretation/c-prime", revision: "09f7d29ad6262f85bc2858f7c468f22d0bd398f3" };
const wayfinder = "central:source:project:quaternal-logic:docs/integrations/epi-logos/VAK-EXPRESSION-WORKFLOW-WAYFINDER.md";
const oikonomia = "central:source:project:quaternal-logic:docs/kernel-rebuild/VAK-OIKONOMIA-KNOWLEDGE-RETURN.md";
const field = "central:source:project:O-I:docs/experience/EXPRESSION-FIELD.md";
const placement = "central:source:control:root:Control/user/placement.json";
const returnDoor = "central:source:control:root:Control/agents/governance/field-and-now/session-work-placement.md";
const anima = ["agent-set/anima"];

export default defineWorkflow({
  source: {
    ref: "workflow-source:01M399B671QTQYNWQ02B8NM941",
    revision: "expression-development-v1",
  },
  workflowKey: "expression-development",
  units: [
    unit({
      key: "nous-open-ground",
      developmentalConcern: "Open the Expression concern and recover its ground before deciding its form",
      requiredDifference: "The live question, the existing Expression and its governing sources are explicit",
      returnContract: "Return the question, the exact Expression and source refs, and what remains open",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/anima-nous"], agentSetRefs: anima },
      praxisRefs: ["skill/ql/gnosis-retrieve", "skill/ql/vak-coordinate-frame", "skill/personal/brainstorming"],
      capabilityRefs: ["capability/source-read", "capability/knowledge-search", "capability/expression-inspect"],
      permittedEffects: ["read Expression, wiki and source material"],
      verificationObligations: ["cite every recovered source with its revision"],
      returnAddress: returns,
      stopConditions: "Stop when the Expression or its subject cannot be identified",
      escalationConditions: "Escalate a request whose meaning depends on an undecided owner position",
      composition: {
        CPF: "dialogical", CT: "CT0", CP: "4.0", CF: "CF1", CFP: "CFP2", CS: "CS1", direction: "forward",
        actor: "agent/anima-nous", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/nous",
        contextResolution: "context-resolution:expression-development/nous",
        sources: [wayfinder, field],
      } satisfies CPrime,
    }),
    unit({
      key: "logos-articulate",
      developmentalConcern: "Articulate the distinctions, constraints and source-bearing form of the Expression",
      requiredDifference: "A precise, usable specification of what the Expression is to become",
      returnContract: "Return the specification with its constraints and the sources it answers to",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/anima-logos"], agentSetRefs: anima },
      praxisRefs: ["skill/ql/vak-evaluate", "skill/personal/writing-plans"],
      capabilityRefs: ["capability/source-read", "capability/expression-inspect"],
      dependencies: ["nous-open-ground"],
      inputs: [{ predecessor: "nous-open-ground", receivingContextRef: "context:expression-development/logos-from-nous" }],
      permittedEffects: ["read Expression and source material", "write a specification into the Return"],
      verificationObligations: ["every constraint traces to a recovered source or an explicit request"],
      returnAddress: returns,
      stopConditions: "Stop when the recovered ground contradicts the request",
      escalationConditions: "Escalate a constraint that only the owner can decide",
      composition: {
        CPF: "dialogical", CT: "CT1", CP: "4.1", CF: "CF2", CFP: "CFP2", CS: "CS2", direction: "forward",
        actor: "agent/anima-logos", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/logos",
        contextResolution: "context-resolution:expression-development/logos",
        sources: [wayfinder, field],
      } satisfies CPrime,
    }),
    unit({
      key: "eros-exchange",
      developmentalConcern: "Bring the specified need into exchange with the Expression powers actually available",
      requiredDifference: "An actual permitted operation on a draft of the Expression, with its observed consequence",
      returnContract: "Return the operation applied, the draft revision and the observed effect",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/anima-eros"], agentSetRefs: anima },
      praxisRefs: ["skill/ql/vak-evaluate", "skill/personal/verification-before-completion"],
      capabilityRefs: ["capability/expression-inspect", "capability/expression-compose", "capability/expression-observe"],
      dependencies: ["logos-articulate"],
      independenceFrom: ["mythos-image"],
      inputs: [{ predecessor: "logos-articulate", receivingContextRef: "context:expression-development/eros-from-logos" }],
      permittedEffects: ["apply validated operations to a separate Expression draft"],
      verificationObligations: ["observe the engine effect at the exact draft revision"],
      returnAddress: returns,
      stopConditions: "Stop when no native operation can express the need; report the missing faculty",
      escalationConditions: "Escalate any operation that would change the original edition",
      composition: {
        CPF: "authorised-undertaking", authority: placement,
        CT: "CT2", CP: "4.2", CF: "CF3", CFP: "CFP1", CS: "CS2", direction: "forward",
        actor: "agent/anima-eros", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/eros",
        contextResolution: "context-resolution:expression-development/eros",
        sources: [wayfinder, field],
      } satisfies CPrime,
    }),
    unit({
      key: "mythos-image",
      developmentalConcern: "Find the organising image of the Expression without losing what it expresses",
      requiredDifference: "A composition proposal that keeps its relation to the concern",
      returnContract: "Return the organising image and how it preserves the concern",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/anima-mythos"], agentSetRefs: anima },
      praxisRefs: ["skill/ql/thought-distil", "skill/personal/brainstorming"],
      capabilityRefs: ["capability/expression-inspect", "capability/knowledge-search"],
      dependencies: ["logos-articulate"],
      independenceFrom: ["eros-exchange"],
      inputs: [{ predecessor: "logos-articulate", receivingContextRef: "context:expression-development/mythos-from-logos" }],
      permittedEffects: ["read Expression material", "propose a composition in the Return"],
      verificationObligations: ["name the pattern and the specification clauses it serves"],
      returnAddress: returns,
      stopConditions: "Stop when the specification leaves no room for a distinct image",
      escalationConditions: "Escalate an image that changes what the work means",
      composition: {
        CPF: "dialogical", CT: "CT3", CP: "4.3", CF: "CF4", CFP: "CFP1", CS: "CS3", direction: "forward",
        actor: "agent/anima-mythos", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/mythos",
        contextResolution: "context-resolution:expression-development/mythos",
        sources: [wayfinder, field],
      } satisfies CPrime,
    }),
    unit({
      key: "anima-conduct",
      developmentalConcern: "Compose the contextual undertaking from the specification, the exchange and the image",
      requiredDifference: "One conducted Expression draft whose voices, boundaries and intended Return are explicit",
      returnContract: "Return the conducted draft revision, which voices shaped it, and what is still unresolved",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/anima"], agentSetRefs: anima },
      praxisRefs: ["skill/ql/anima-orchestration", "skill/personal/subagent-driven-development", "skill/personal/dispatching-parallel-agents"],
      capabilityRefs: ["capability/expression-compose", "capability/expression-perform", "capability/expression-observe"],
      dependencies: ["logos-articulate", "eros-exchange", "mythos-image"],
      inputs: [
        { predecessor: "logos-articulate", receivingContextRef: "context:expression-development/anima-from-logos" },
        { predecessor: "eros-exchange", receivingContextRef: "context:expression-development/anima-from-eros" },
        { predecessor: "mythos-image", receivingContextRef: "context:expression-development/anima-from-mythos" },
      ],
      permittedEffects: ["compose and perform on the Expression draft", "save a new draft edition"],
      verificationObligations: ["observe the performed draft in the engine, not only the returned request"],
      returnAddress: returns,
      stopConditions: "Stop when the exchange and the image cannot both be honoured; return the conflict",
      escalationConditions: "Escalate publication, sharing or replacement of the original edition",
      composition: {
        CPF: "authorised-undertaking", authority: placement,
        CT: "CT4", CP: "4.4", CF: "CF5", CFP: "CFP2", CS: "CS4", direction: "forward",
        actor: "agent/anima", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/anima",
        contextResolution: "context-resolution:expression-development/anima",
        sources: [wayfinder, oikonomia, field],
      } satisfies CPrime,
    }),
    unit({
      key: "psyche-continuity",
      developmentalConcern: "Steward the continuity of the conducted Expression across context, actors and occasions",
      requiredDifference: "The draft is recoverable in its situation: edition, occasion and open threads are placed",
      returnContract: "Return the continuity record: edition, occasion, carried threads and their next review",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/anima-psyche"], agentSetRefs: anima },
      praxisRefs: ["skill/ql/day-night-pass", "skill/personal/executing-plans"],
      capabilityRefs: ["capability/now-read", "capability/expression-inspect"],
      dependencies: ["anima-conduct"],
      inputs: [{ predecessor: "anima-conduct", receivingContextRef: "context:expression-development/psyche-from-anima" }],
      permittedEffects: ["read the NOW field and the Expression draft"],
      verificationObligations: ["every carried thread names its live reason and next review"],
      returnAddress: returns,
      stopConditions: "Stop when the draft edition is not retrievable",
      escalationConditions: "Escalate continuity that would need personal or private context",
      composition: {
        CPF: "dialogical", CT: "CT4b'", CP: "4.4", CF: "CF6", CFP: "CFP2", CS: "CS4", direction: "returning",
        actor: "agent/anima-psyche", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/psyche",
        contextResolution: "context-resolution:expression-development/psyche",
        sources: [oikonomia, returnDoor],
      } satisfies CPrime,
    }),
    unit({
      key: "sophia-integrate",
      developmentalConcern: "Integrate the performed differences and unresolved questions into renewed ground",
      requiredDifference: "A source-qualified synthesis of what the Expression became and what it asks next",
      returnContract: "Return the synthesis, the questions it leaves open and the sources it rests on",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/anima-sophia"], agentSetRefs: anima },
      praxisRefs: ["skill/ql/thought-distil", "skill/personal/verification-before-completion"],
      capabilityRefs: ["capability/source-read", "capability/expression-inspect"],
      dependencies: ["psyche-continuity"],
      inputs: [{ predecessor: "psyche-continuity", receivingContextRef: "context:expression-development/sophia-from-psyche" }],
      permittedEffects: ["read the conducted draft and continuity record", "write the synthesis into the Return"],
      verificationObligations: ["distinguish what was observed from what is inferred"],
      returnAddress: returns,
      stopConditions: "Stop when the performed draft cannot be compared with the specification",
      escalationConditions: "Escalate a synthesis that would change authored ground",
      composition: {
        CPF: "dialogical", CT: "CT5", CP: "4.5", CF: "CF7", CFP: "CFP2", CS: "CS5", direction: "returning",
        actor: "agent/anima-sophia", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/sophia",
        contextResolution: "context-resolution:expression-development/sophia",
        sources: [wayfinder, oikonomia],
      } satisfies CPrime,
    }),
    unit({
      key: "aletheia-disclose-return",
      developmentalConcern: "Disclose what was actually performed, compare it with the intent, and return it",
      requiredDifference: "The performed trajectory and its synthesis reach the NOW field as an attributed Return",
      returnContract: "Return the disclosure: intent against performance, evidence refs and the Return record ref",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia"], agentSetRefs: ["agent-set/aletheia"] },
      praxisRefs: ["skill/ql/aletheia-stack-traverse", "skill/personal/verification-before-completion"],
      capabilityRefs: ["capability/now-return", "capability/expression-observe"],
      dependencies: ["sophia-integrate"],
      inputs: [{ predecessor: "sophia-integrate", receivingContextRef: "context:expression-development/aletheia-from-sophia" }],
      permittedEffects: ["write one attributed Return to the project NOW field"],
      verificationObligations: ["the Return points at the performed draft edition and its evidence"],
      returnAddress: returns,
      stopConditions: "Stop when there is no performed evidence to disclose",
      escalationConditions: "Escalate Recognition decisions to the owner; never promote on its own",
      composition: {
        CPF: "authorised-undertaking", authority: returnDoor,
        CT: "CT5", CP: "4.5", CF: "CF7", CFP: "CFP0", CS: "CS5", direction: "returning",
        actor: "agent/aletheia", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:expression-development/aletheia",
        contextResolution: "context-resolution:expression-development/aletheia",
        sources: [oikonomia, returnDoor],
      } satisfies CPrime,
    }),
  ],
  barriers: [
    barrier({ key: "chord-resolves", waitsFor: ["eros-exchange", "mythos-image"], releases: ["anima-conduct"] }),
  ],
});
