// Technē on a wiki constellation: Aletheia's specialists blueprint, distil,
// translate and relate a constellation, Agora examines the fused readings,
// Zeithoven proposes the next form, and Aletheia returns the revision.
//
// A Factory workflow source (restricted TypeScript data, never executed).
// Check it with: factory workflow check workflows/techne-constellation.workflow.ts --json
// The root wiki is agent-maintained knowledge, never edited directly: the
// constellation revision travels as a Return through the NOW promotion door.
import { defineWorkflow, unit, barrier } from "@epilogos/factory-workflow";
import type { CPrime } from "@epilogos/ql-vak";

const subject = "central:wiki:root";
const basis = "wiki-revision-50";
const whole = "central:source:control:root:Control/agents/wiki/wiki.json";
const returns = "central:source:control:root:Control/agents/now";
const cprime = { ref: "ql/interpretation/c-prime", revision: "09f7d29ad6262f85bc2858f7c468f22d0bd398f3" };
const fieldLock = "central:source:project:quaternal-logic:docs/integrations/epi-logos/TA-ONTA-FULL-FIELD-LOCK.md";
const oikonomia = "central:source:project:quaternal-logic:docs/kernel-rebuild/VAK-OIKONOMIA-KNOWLEDGE-RETURN.md";
const wikiLaw = "central:source:control:root:Control/agents/governance/field-and-now/wiki-field-law.md";
const aletheia = ["agent-set/aletheia"];

export default defineWorkflow({
  source: {
    ref: "workflow-source:01M399B69V0AWMNFPQ9TE1FHGJ",
    revision: "techne-constellation-v1",
  },
  workflowKey: "techne-constellation",
  units: [
    unit({
      key: "anansi-blueprint",
      developmentalConcern: "Coordinate the constellation: its members, relations and the gaps between what is authored and what is held",
      requiredDifference: "A blueprint of the constellation with its gaps and the questions each specialist must answer",
      returnContract: "Return the blueprint: member refs, typed relations, gaps and assigned questions",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia-anansi"], agentSetRefs: aletheia },
      praxisRefs: ["skill/ql/anansi", "skill/ql/vak-coordinate-frame", "skill/personal/writing-plans"],
      capabilityRefs: ["capability/wiki-read", "capability/source-read"],
      permittedEffects: ["read the root wiki and its cited sources"],
      verificationObligations: ["every member and relation cites its wiki node or source"],
      returnAddress: returns,
      stopConditions: "Stop when the constellation cannot be bounded to named members",
      escalationConditions: "Escalate a gap that needs an authored owner decision",
      composition: {
        CPF: "dialogical", CT: "CT1", CP: "4.1", CF: "CF2", CFP: "CFP2", CS: "CS2", direction: "forward",
        actor: "agent/aletheia-anansi", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:techne-constellation/anansi",
        contextResolution: "context-resolution:techne-constellation/anansi",
        sources: [fieldLock, wikiLaw],
      } satisfies CPrime,
    }),
    unit({
      key: "moirai-distil",
      developmentalConcern: "Distil the evidence the constellation actually rests on through the source-defined modes",
      requiredDifference: "The constellation's evidence is queried and reflected, with what it does not support stated",
      returnContract: "Return the distilled evidence per member and the claims it cannot support",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia-moirai"], agentSetRefs: aletheia },
      praxisRefs: ["skill/ql/gnosis-retrieve", "skill/ql/thought-distil"],
      capabilityRefs: ["capability/wiki-read", "capability/knowledge-search"],
      dependencies: ["anansi-blueprint"],
      independenceFrom: ["mercurius-translate", "janus-temporal-seam"],
      inputs: [{ predecessor: "anansi-blueprint", receivingContextRef: "context:techne-constellation/moirai-from-anansi" }],
      permittedEffects: ["read wiki nodes and their sources"],
      verificationObligations: ["separate observed evidence from inference"],
      returnAddress: returns,
      stopConditions: "Stop when the blueprint names no evidence-bearing member",
      escalationConditions: "Escalate contradictory sources",
      composition: {
        CPF: "dialogical", CT: "CT3", CP: "4.0", CF: "CF1", CFP: "CFP3", CS: "CS1", direction: "forward",
        actor: "agent/aletheia-moirai", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:techne-constellation/moirai",
        contextResolution: "context-resolution:techne-constellation/moirai",
        sources: [fieldLock, oikonomia],
      } satisfies CPrime,
    }),
    unit({
      key: "mercurius-translate",
      developmentalConcern: "Translate the constellation across the domains its members come from",
      requiredDifference: "Each cross-domain relation is stated in the terms of both domains",
      returnContract: "Return the translations and the relations that do not survive translation",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia-mercurius"], agentSetRefs: aletheia },
      praxisRefs: ["skill/ql/vak-coordinate-frame", "skill/ql/vak-evaluate"],
      capabilityRefs: ["capability/wiki-read", "capability/source-read"],
      dependencies: ["anansi-blueprint"],
      independenceFrom: ["moirai-distil", "janus-temporal-seam"],
      inputs: [{ predecessor: "anansi-blueprint", receivingContextRef: "context:techne-constellation/mercurius-from-anansi" }],
      permittedEffects: ["read wiki nodes and their sources"],
      verificationObligations: ["each translation names both source domains"],
      returnAddress: returns,
      stopConditions: "Stop when the constellation is single-domain",
      escalationConditions: "Escalate a translation that changes a canonical meaning",
      composition: {
        CPF: "dialogical", CT: "CT2", CP: "4.2", CF: "CF3", CFP: "CFP3", CS: "CS2", direction: "forward",
        actor: "agent/aletheia-mercurius", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:techne-constellation/mercurius",
        contextResolution: "context-resolution:techne-constellation/mercurius",
        sources: [fieldLock],
      } satisfies CPrime,
    }),
    unit({
      key: "janus-temporal-seam",
      developmentalConcern: "Relate the constellation's occasions: what it held before, holds now and is opening toward",
      requiredDifference: "The temporal seams of the constellation are explicit, with the day and occasion of each",
      returnContract: "Return the seams: prior and current readings, their occasions and the threshold between them",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia-janus"], agentSetRefs: aletheia },
      praxisRefs: ["skill/ql/day-night-pass"],
      capabilityRefs: ["capability/wiki-read", "capability/now-read"],
      dependencies: ["anansi-blueprint"],
      independenceFrom: ["moirai-distil", "mercurius-translate"],
      inputs: [{ predecessor: "anansi-blueprint", receivingContextRef: "context:techne-constellation/janus-from-anansi" }],
      permittedEffects: ["read wiki history, day readings and the NOW field"],
      verificationObligations: ["every seam cites the dated reading it relies on"],
      returnAddress: returns,
      stopConditions: "Stop when no prior reading of the constellation exists",
      escalationConditions: "Escalate an archive gap instead of reconstructing it",
      composition: {
        CPF: "dialogical", CT: "CT4b'", CP: "4.4", CF: "CF6", CFP: "CFP3", CS: "CS4", direction: "returning",
        actor: "agent/aletheia-janus", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:techne-constellation/janus",
        contextResolution: "context-resolution:techne-constellation/janus",
        sources: [fieldLock, oikonomia],
      } satisfies CPrime,
    }),
    unit({
      key: "agora-aggregate",
      developmentalConcern: "Examine the three readings together and aggregate what they establish",
      requiredDifference: "One examined aggregate of the constellation, with agreements, conflicts and absorbed practice",
      returnContract: "Return the aggregate, each reading's contribution and the conflicts left open",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia-agora"], agentSetRefs: aletheia },
      praxisRefs: ["skill/ql/vak-evaluate", "skill/personal/verification-before-completion"],
      capabilityRefs: ["capability/wiki-read"],
      dependencies: ["anansi-blueprint", "moirai-distil", "mercurius-translate", "janus-temporal-seam"],
      inputs: [
        { predecessor: "anansi-blueprint", receivingContextRef: "context:techne-constellation/agora-from-anansi" },
        { predecessor: "moirai-distil", receivingContextRef: "context:techne-constellation/agora-from-moirai" },
        { predecessor: "mercurius-translate", receivingContextRef: "context:techne-constellation/agora-from-mercurius" },
        { predecessor: "janus-temporal-seam", receivingContextRef: "context:techne-constellation/agora-from-janus" },
      ],
      permittedEffects: ["read the three readings and the blueprint"],
      verificationObligations: ["the aggregate attributes each claim to the reading that supports it"],
      returnAddress: returns,
      stopConditions: "Stop when fewer than two readings returned",
      escalationConditions: "Escalate an irreconcilable conflict",
      composition: {
        CPF: "dialogical", CT: "CT3", CP: "4.3", CF: "CF4", CFP: "CFP2", CS: "CS3", direction: "forward",
        actor: "agent/aletheia-agora", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:techne-constellation/agora",
        contextResolution: "context-resolution:techne-constellation/agora",
        sources: [fieldLock],
      } satisfies CPrime,
    }),
    unit({
      key: "zeithoven-next-form",
      developmentalConcern: "Develop the next form of the constellation from the examined aggregate",
      requiredDifference: "A proposed constellation revision (and, where fitting, an Expression of it) ready for return",
      returnContract: "Return the proposed revision as a diff against the current constellation, with its Expression proposal",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia-zeithoven"], agentSetRefs: aletheia },
      praxisRefs: ["skill/personal/brainstorming", "skill/personal/writing-plans"],
      capabilityRefs: ["capability/wiki-read", "capability/expression-compose"],
      dependencies: ["agora-aggregate"],
      inputs: [{ predecessor: "agora-aggregate", receivingContextRef: "context:techne-constellation/zeithoven-from-agora" }],
      permittedEffects: ["propose a constellation revision and an Expression draft in the Return"],
      verificationObligations: ["every proposed change traces to the aggregate"],
      returnAddress: returns,
      stopConditions: "Stop when the aggregate supports no change",
      escalationConditions: "Escalate a revision that would change authored ground",
      composition: {
        CPF: "dialogical", CT: "CT5", CP: "4.5", CF: "CF7", CFP: "CFP2", CS: "CS5", direction: "forward",
        actor: "agent/aletheia-zeithoven", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:techne-constellation/zeithoven",
        contextResolution: "context-resolution:techne-constellation/zeithoven",
        sources: [fieldLock, wikiLaw],
      } satisfies CPrime,
    }),
    unit({
      key: "aletheia-return-revision",
      developmentalConcern: "Crystallise the proposed constellation revision and return it through the wiki return door",
      requiredDifference: "The revision reaches the root NOW field as an attributed Return ready for wiki promotion",
      returnContract: "Return the Return record ref, the revision it carries and the evidence behind it",
      subjectRef: subject,
      basisRevision: basis,
      agentRequirements: { agentRefs: ["agent/aletheia"], agentSetRefs: aletheia },
      praxisRefs: ["skill/ql/aletheia-stack-traverse", "skill/ql/thought-distil"],
      capabilityRefs: ["capability/now-return", "capability/wiki-return"],
      dependencies: ["zeithoven-next-form"],
      inputs: [{ predecessor: "zeithoven-next-form", receivingContextRef: "context:techne-constellation/aletheia-from-zeithoven" }],
      permittedEffects: ["write one attributed Return to the root NOW field"],
      verificationObligations: ["the Return carries lineage to the aggregate and each reading"],
      returnAddress: returns,
      stopConditions: "Stop when there is no proposed revision to return",
      escalationConditions: "Never edit wiki.json directly; escalate promotion decisions to the wiki owner",
      composition: {
        CPF: "authorised-undertaking", authority: wikiLaw,
        CT: "CT5", CP: "4.5", CF: "CF7", CFP: "CFP0", CS: "CS5", direction: "returning",
        actor: "agent/aletheia", interpretation: cprime, whole: whole,
        resolvePath: "resolve-scoped-path:techne-constellation/aletheia",
        contextResolution: "context-resolution:techne-constellation/aletheia",
        sources: [wikiLaw, oikonomia],
      } satisfies CPrime,
    }),
  ],
  barriers: [
    barrier({
      key: "readings-fuse",
      waitsFor: ["moirai-distil", "mercurius-translate", "janus-temporal-seam"],
      releases: ["agora-aggregate"],
    }),
  ],
});
