#!/usr/bin/env python3
"""Compile the locked Vortex CSV into exact source-token access, not new canon."""
import argparse
import csv
import hashlib
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "migration/epi-kernel/m1-return/vortex-modulae.csv"

def generate():
    raw = SOURCE.read_bytes()
    lock = json.loads((SOURCE.parent / "source-lock.json").read_text())
    item = next(f for f in lock["files"] if f["local_path"].endswith("vortex-modulae.csv"))
    assert hashlib.sha256(raw).hexdigest() == item["sha256"]
    with SOURCE.open(encoding="utf-8-sig", newline="") as f:
        table = list(csv.reader(f))
    assert "No digi-rooting" in table[0] and "Digi-rooting" in table[34]
    entries = []
    for family in range(6):
        for row in range(12):
            for col in range(12):
                y, x = 4 + row + (row >= 10), [22,3,42,64,87,108][family] + col + (col >= 10)
                entries.append(dict(family=family, row12=row, col12=col,
                    raw_literal=table[y][x], digit_root_literal=table[y+34][x],
                    csv_raw_row=y+1, csv_dr_row=y+35, csv_column=x+1))
    doc = dict(schema="ql.m1.source-literals/v1", source_sha256=item["sha256"],
               source_git_blob=item["git_blob"], source_revision=lock["revision"], cells=entries)
    j = json.dumps(doc, ensure_ascii=False, indent=2) + "\n"
    c = "/* Generated by scripts/generate-m1-source.py from the byte-locked CSV. */\n"
    c += "static const QL_M1_SourceCell source_cells[864] = {\n"
    for e in entries:
        c += "    {%s,%s,%s,%s,%s,%s,%s,%s},\n" % (e["family"],e["row12"],e["col12"],
            json.dumps(e["raw_literal"]),json.dumps(e["digit_root_literal"]),
            e["csv_raw_row"],e["csv_dr_row"],e["csv_column"])
    c += "};\n"
    return {"fixtures/kernel/m1-source-literals-v1.json":j, "c/src/m1_source_data.inc":c}

def main():
    p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");a=p.parse_args()
    for path,text in generate().items():
        if a.write: (ROOT/path).write_text(text)
        else: assert (ROOT/path).read_text()==text, f"stale M1 source tokens: {path}"
    print("M1: 864 source cells / 1728 literal tokens exactly compiled")
if __name__ == "__main__": main()
