#!/bin/sh
# O:I managed source install for Quaternal Logic.
#
# Builds the `ql` command and the native Expression owners it relies on at the
# same committed cut: the Rust hosts (ql-field-host, ql-focused-host) and the
# C++ continuous worker (ql-field-worker). O:I stages all of them beside `ql`
# in one content-addressed product directory, so a host can never pair with a
# worker from another revision.
#
# Honours CARGO_TARGET_DIR (the O:I persistent build cache); every executable
# lands in "$CARGO_TARGET_DIR/release".
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
target=${CARGO_TARGET_DIR:-$root/target}
release="$target/release"

cargo build --manifest-path "$root/Cargo.toml" --workspace --locked --release

if [ "$(uname -s)" = Darwin ]; then
  arch=$(uname -m)
  # Link json-c for the architecture actually being built.
  if [ "$arch" = arm64 ] && [ -d /opt/homebrew/opt/json-c/lib/pkgconfig ]; then
    PKG_CONFIG_PATH=/opt/homebrew/opt/json-c/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    export PKG_CONFIG_PATH
  fi
  # A Command Line Tools install whose libc++ headers did not land cannot
  # compile <cassert>. Use the SDK's complete libc++ headers instead, and say so.
  probe=$(mktemp -d)
  printf '#include <cassert>\nint main(){}\n' > "$probe/p.cpp"
  if ! c++ -std=c++17 -fsyntax-only "$probe/p.cpp" 2>/dev/null; then
    for sdk in $(ls -d /Library/Developer/CommandLineTools/SDKs/MacOSX*.sdk 2>/dev/null | sort -rV); do
      if [ -f "$sdk/usr/include/c++/v1/cassert" ]; then
        CPLUS_INCLUDE_PATH="$sdk/usr/include/c++/v1"
        export CPLUS_INCLUDE_PATH
        echo "oi-source-install: toolchain libc++ headers missing; using $sdk" >&2
        break
      fi
    done
  fi
  rm -rf "$probe"
fi

build=$(mktemp -d)
trap 'rm -rf "$build"' EXIT
make -C "$root/c" all BUILD_DIR="$build/c"
make -C "$root/cpp" test BUILD_DIR="$build/cpp" LIB="$build/c/libql-mef-c.a"
mkdir -p "$release"
install -m755 "$build/cpp/ql-field-worker" "$release/ql-field-worker"

# ql-sky: the accepted dated-sky provider (K8-SKY-CONTRACT) as one executable.
# It carries the provider and the two source files it verifies its planet
# binding against, extracts them once into a digest-named cache directory and
# runs the pinned Kerykeion/pyswisseph under a uv-managed CPython.
payload=$(cd "$root" && tar -cf - providers/sky/kerykeion_snapshot.py providers/sky/requirements.txt \
  vendor/epi-kernel/reference/include/m2.h fixtures/kernel/m2-retained-c-v1.json | gzip -n | base64 | tr -d '\n')
digest=$(printf %s "$payload" | shasum -a 256 | cut -c1-16)
{
  printf '#!/bin/sh\n# Generated by scripts/oi-source-install.sh; payload %s\nset -eu\n' "$digest"
  printf 'payload=%s\n' "$payload"
  printf 'dir="${XDG_CACHE_HOME:-$HOME/.cache}/ql-sky/%s"\n' "$digest"
  # A desktop app's PATH rarely holds the user's tool directories; keep the uv
  # found at install time as the fallback.
  printf 'installed_uv=%s\n' "$(command -v uv || true)"
  cat <<'SH'
if [ ! -f "$dir/providers/sky/kerykeion_snapshot.py" ]; then
  tmp="$dir.tmp.$$"; mkdir -p "$tmp"
  printf %s "$payload" | base64 -d | gzip -dc | tar -xf - -C "$tmp"
  mv "$tmp" "$dir" 2>/dev/null || rm -rf "$tmp"
fi
uv=$(command -v uv || true); [ -n "$uv" ] || uv=$installed_uv
[ -n "$uv" ] && [ -x "$uv" ] || { echo '{"schema":"ql.sky-error/v1","error":"uv is required for the dated-sky provider","snapshot":null}' >&2; exit 2; }
exec "$uv" run --quiet --no-project --python-preference only-managed --python 3.13 \
  --with-requirements "$dir/providers/sky/requirements.txt" \
  python "$dir/providers/sky/kerykeion_snapshot.py" "$@"
SH
} > "$release/ql-sky"
chmod 755 "$release/ql-sky"
