#!/usr/bin/env bash
# Real physical/audio component and paired producer floor. This does not claim
# an installed app, device latency, fifteen-minute workload or human acceptance.
set -euo pipefail
TASK_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
TASK_OUTPUT="$TASK_ROOT/target/physical-musical"
mkdir -p "$TASK_OUTPUT"
cd "$TASK_ROOT"
make -C c all
make -C cpp test BUILD_DIR="$TASK_OUTPUT/native" -j1

# Discover paired suites from native source. Each receives the exact binary
# just built from the same native source/registry, never a supplied mock frame.
for source in crates/ql-mef/tests/*_native_wire.rs; do
  [[ -f "$source" ]] || continue
  suite=${source##*/}; suite=${suite%.rs}
  native=${suite/_native_wire/_wire}
  binary="$TASK_OUTPUT/native/$native-test"
  [[ -x "$binary" ]] || { printf 'Missing paired native producer binary: %s\n' "$binary" >&2; exit 1; }
  QL_NATIVE_WIRE_TEST="$binary" cargo test -p ql-mef --locked --test "$suite" -- --ignored
done

# Keep the real Rust producer and the C++ consumer in one executed passage.
# These are finite component fixtures; they are not installed host authority.
TASK_PACKET_OUTPUT="$TASK_OUTPUT/performance-packets"
mkdir -p "$TASK_PACKET_OUTPUT"
QL_PERFORMANCE_PACKET_OUTPUT="$TASK_PACKET_OUTPUT" cargo test -p ql-mef --locked --test performance_audio actual_vimarsha_determinant_changes_octet_with_fixed_keys_metric_body_and_policy -- --exact
"$TASK_OUTPUT/native/native_performance_packet-test" "$TASK_PACKET_OUTPUT"
"$TASK_OUTPUT/native/independent_clock_admission_packet-test" "$TASK_PACKET_OUTPUT"
"$TASK_OUTPUT/native/performance_management_packet-test" "$TASK_PACKET_OUTPUT"
"$TASK_OUTPUT/native/performance_application_order_packet-test" "$TASK_PACKET_OUTPUT"
v_order_nonce=$(python3 -c 'import uuid; print(uuid.uuid4().hex)')
TASK_MANAGED_ORDER_OUTPUT="$TASK_OUTPUT/managed-application-order-${GITHUB_RUN_ID:-local}-${GITHUB_RUN_ATTEMPT:-1}-$v_order_nonce"
"$TASK_OUTPUT/native/performance_managed_application_order_packet-test" "$TASK_PACKET_OUTPUT" "$TASK_MANAGED_ORDER_OUTPUT"
QL_NATIVE_RECEIVING_ADMISSION_TEST="$TASK_OUTPUT/native/performance_receiving_admission-test" cargo test -p ql-mef --locked --test performance_receiving_admission -- --ignored

# Actual post-command SourceForm material and its genuine mechanical body:
# the same q/v emits both copied visible positions and native PCM.
TASK_MATERIAL_OUTPUT="$TASK_OUTPUT/material-fold"
mkdir -p "$TASK_MATERIAL_OUTPUT"
QL_MATERIAL_FOLD_FIXTURE="$TASK_MATERIAL_OUTPUT/native-fold.json" cargo test -p ql-mef --locked --test m3_material_fold
"$TASK_OUTPUT/native/material_fold_body-test" "$TASK_MATERIAL_OUTPUT/native-fold.json" "$TASK_MATERIAL_OUTPUT/physical-observed.json" "$TASK_MATERIAL_OUTPUT/captured-native.wav"
# Preserve the actual original pre-material source and applied input journal
# for the existing C Scene/Act gate. Its optional offline fingerprint belongs
# to that native owner and is supplied by the ordinary C fixture gate.
TASK_MANAGEMENT_OUTPUT="$TASK_OUTPUT/management-artifacts"
mkdir -p "$TASK_MANAGEMENT_OUTPUT"
"$TASK_OUTPUT/native/performance_management_artifacts_packet-test" "$TASK_PACKET_OUTPUT" "$TASK_MANAGEMENT_OUTPUT"

# Retain the same native M3 score/return and real A/P continuation for the
# existing Expression/Act tests. Full paused voice/body state is generated by
# the actual C++ owner and independently replayed before it is emitted.
cargo run --quiet -p ql-mef --locked --example retained-performance-fixture > "$TASK_OUTPUT/retained-performance-fixture.json"
"$TASK_OUTPUT/native/retained_performance_checkpoint_wire-test" "$TASK_OUTPUT/retained-performance-fixture.json" > "$TASK_OUTPUT/retained-performance-checkpoint-fixture.json"

# Independent V/#293 trials use the same compiled native producer. Copy the
# unchanged verifier into its bounded evidence directory before invocation.
cargo build -p ql-mef --locked --example m2_engine
TASK_INDEPENDENT="$TASK_OUTPUT/independent"
mkdir -p "$TASK_INDEPENDENT"
cp scripts/test-m2-producer-negatives.py "$TASK_INDEPENDENT/driver.py"
v_candidate_revision=$(git rev-parse HEAD)
v_source_revision=$(python3 -c 'import json; print(json.load(open("fixtures/kernel/m2-correspondences-v1.json"))["source_revision"])')
v_trial_nonce=$(python3 -c 'import uuid; print(uuid.uuid4().hex)')
python3 "$TASK_INDEPENDENT/driver.py" \
  --producer target/debug/examples/m2_engine \
  --fixture fixtures/kernel/m2-condition-request-v1.json \
  --output "$TASK_INDEPENDENT/run-${GITHUB_RUN_ID:-local}-${GITHUB_RUN_ATTEMPT:-1}-$v_trial_nonce" \
  --candidate-revision "$v_candidate_revision" \
  --source-revision "$v_source_revision"
